### ISSUE TITLE
Add login support for mintmanga.live

### ISSUE THREAD

**Issue by Couch0wl** [HDoujinDownloader/HDoujinDownloader#102]
Pages from https://mintmanga.live are not being captured.

**Comment by HDoujinDownloader** [comment]
It looks like they now require a login to access mature content.

I can add login support, but it looks like their registration form is currently broken (returns an error when you try to submit your registration). Let me know when it's working again and I'll take another look.

**Comment by Couch0wl** [comment]
Yes, I do observe a problem with the registration. I used the workaround to create an account, I can send login information. Where can I send them?

**Comment by HDoujinDownloader** [comment]
Thanks for offering to help. If you want, you can send the login details through the [contact form](https://doujindownloader.com/contact/), or to the email address on the "About" tab of HDoujin Downloader.

What is the workaround you used to create the account, by the way?

**Comment by Couch0wl** [comment]
I sent the credentials via the feedback form.
I created an account through FB, then unlinked the FB account, changed email.

**Comment by HDoujinDownloader** [comment]
Thank you! I was able to create an account myself with the workaround you provided.

It turns out the solution was simpler than it seemed. The `mature=1` parameter you needed to access them before just changed to `mtr=true`. However, this did not become apparent until logging in.

They should be working fine now, but let me know if you have any trouble.

**Comment by kifat** [comment]
Now site is require a login to access mature content, shapters download failed

**Comment by Couch0wl** [comment]
Yes, I created a new issue in December, but the project seems to be in hibernation for now.
https://github.com/HDoujinDownloader/HDoujinDownloader/issues/167
