### ISSUE TITLE
Add option to download WebP images from LezhinUS

### ISSUE THREAD

**Issue by Fallen98** [HDoujinDownloader/HDoujinDownloader#111]
Would you be able to add an option to download the WebP version for the images from LezhinUS?

**Comment by HDoujinDownloader** [comment]
Yeah, sure! The setting has now been added, and you can find it under **_Tools > Site preferences > Lezhin Comics_**.

Just make sure you disable the WEBP -> JPEG conversion rule if you want them to stay as WEBP images.
