### ISSUE TITLE
HDoujin showing unreleased chapters from Tapas

### ISSUE THREAD

**Issue by Fallen98** [HDoujinDownloader/HDoujinDownloader#112]
When adding a link from Tapas it shows also the unreleased chapter, this gives problems when checking for new chapters

An example is: https://tapas.io/series/between-the-stars/info

**Comment by HDoujinDownloader** [comment]
Thanks for including an example URL. I was able to verify the problem, and it's now been fixed (e3e818a2445122e2ab0ee06c66b60374af8eab60).
