### ISSUE TITLE
NHentai Cloudfare Issue

### ISSUE THREAD

**Issue by calne-ca** [HDoujinDownloader/HDoujinDownloader#117]
A few days ago downloads for nhentai.net stopped working with the error message *Your connection to nhentai.net is being blocked by Cloudflare's anti-bot challenge*. I already read the [Cloudfare wiki page](https://github.com/HDoujinDownloader/HDoujinDownloader/wiki/Cloudflare) and tried all available solvers in headless and non-headless mode but none of them worked.

**Comment by HDoujinDownloader** [comment]
Yes, nHentai has been enabling Cloudflare's anti-bot protections on and off for the past few days. It's usually not enabled for longer than a few hours, but it seems to be happening more frequently.

Just to be sure: Did you try using the [FlareSolverr plugin](https://github.com/HDoujinDownloader/HDoujinDownloader/wiki/FlareSolverr-IUAM-Challenge-Solver)? FlareSolverr v2.2.4 is able to resolve the challenge, and then downloads will continue normally. Currently this is the only solver that works.

**Comment by calne-ca** [comment]
I download this plugin, yes. I put the zip into a *plugins* folder in the installation directory. In HDD I went to the settings in the Cloudflare solvers section and chose *FlareSolverr IUAM Challenge Solver* and tried both the headless and non-headless mode. For the non-headless mode I also tried both firefox and chrome.

![image](https://user-images.githubusercontent.com/26715487/166099021-8baf909d-ad21-43c3-b30d-8cecb5d2a46e.png)

**Comment by HDoujinDownloader** [comment]
Thanks for giving it a shot. Could you please go to **_Tools > Log Viewer_**, attempt to add a URL from nhentai to the download queue, and then send me the contents of the log? It'll show what FlareSolverr is doing and (hopefully) why it's not working.

**Comment by calne-ca** [comment]
![image](https://user-images.githubusercontent.com/26715487/166114455-8a8f5a6f-a21b-4aab-a634-2f7870c3cecb.png)

The problem was sitting in front of the computer, putting the plugin into the wrong directory >_>
Now that I put it into the correct directory it works!

**Comment by HDoujinDownloader** [comment]
It seems nhentai has disabled Cloudflare again, although some users are still encountering problems with it even when using the FlareSolverr plugin. I think more advanced protections (e.g. captchas) are being enabled for certain IP addresses.

For any user affected by this, my current suggestion is to try using a proxy or VPN.

**Comment by Romangelo** [comment]
Why doesn't it work?

![FSV](https://user-images.githubusercontent.com/25454806/171827199-50ccae9d-1fd3-4df9-bb33-9937e714ee4a.png)

**Comment by Romangelo** [comment]
Ah, it's working now. It seems that my IP address wasn't being loved by either Flaresolverr or nhentai, including some VPN's IPs. Finally found an IP that can download.

**Comment by HDoujinDownloader** [comment]
@Romangelo I noticed you commented about this problem being resolved but I can't seem to find the comment anymore; I imagine you're having this problem again.

It seems like FlareSolverr either isn't running, or is listening on a non-default port. If you scroll up in the log, you should find something like:

```
12:46:58 flaresolver [i] Starting FlareSolverr service
```

Does it seem to encounter any problems when starting up FlareSolverr after that line?

**Comment by Romangelo** [comment]
Yes, I've been dealing with this problem. It was kinda on and off, until I realized that I did something wrong. The problem was that I extracted the plugin out of its zipped file when I shouldn't do that. Now with the zipped file in the plugin folder as is, it's working perfectly.

Thanks for the reply.
