### ISSUE TITLE
No Metadata and images downloaded from nHentai

### ISSUE THREAD

**Issue by WorldTeacher** [HDoujinDownloader/HDoujinDownloader#127]
I just tried to download some galleries from nhentai, but neither the pages nor the metadata got downloaded.
I have both added the flaresolver and login credentials for nhentai.

the downloader created the info.txt file, but the data in it was not usable at all.
The Folder does not show the gallery name, instead it shows the id associated with the doujin from nHentai, and the info.txt only has the nhentai url in it.

**Comment by HDoujinDownloader** [comment]
This is what happens when HDoujin Downloader is unable to connect to the website-- It falls back to using the gallery ID instead of the title, as you're experiencing.

It's possible that this is because of something other than Cloudflare (as you stated you're already using the [FlareSolverr plugin](https://github.com/HDoujinDownloader/HDoujinDownloader/wiki/FlareSolverr-IUAM-Challenge-Solver)). Open the log viewer by going to **_Tools > Log Viewer_**, and then try to add a URL to the download queue. Copy the contents of the log here, and I'll take a look.

**Comment by WorldTeacher** [comment]
sorry for the late reply, I was not on my pc yesterday.

Here's the requested logfile. This was generated using this [flaresolver](https://github.com/FlareSolverr/FlareSolverr/releases/download/v2.2.4/flaresolverr-v2.2.4-windows-x64.zip
[log flaresolver 2.2.4.log](https://github.com/HDoujinDownloader/HDoujinDownloader/files/9037003/log.flaresolver.2.2.4.log)
)

**Comment by HDoujinDownloader** [comment]
It's okay! Thanks for including the log file.

It looks like it's using an outdated version of the nHentai module. I'm not sure why it's not downloading module updates automatically, but you can try syncing manually by going to **_Tools > Module Browser_**, selecting the "Official Lua Repository", going to the "Options" tab, and finally clicking the "Sync Now" button.

If that fails for some reason (GitHub blocked by ISP?), you can also update your modules by following the instructions [here](https://github.com/HDoujinDownloader/HDoujinDownloader/wiki/Module-Repositories#syncing-modules).

If you only want to update the nHentai module, you can also just download the latest version [here](https://raw.githubusercontent.com/HDoujinDownloader/HDoujinDownloader/master/modules/lua/NHentai.lua) and replace the "NHentai.lua" file in the "modules\lua\" folder with that one.

Regardless of how you do it, it should start working after that!

**Comment by WorldTeacher** [comment]
Thanks for that ^^

Now the modules are working, but when I try to add a link,  Cloudflare times out, no matter what I try (flaresolver enabled and disabled)
Here's the new log:
[flaretimeout.log](https://github.com/HDoujinDownloader/HDoujinDownloader/files/9058288/flaretimeout.log)

I'll do a reboot of my system once some tasks are done running (~6h) maybe that'll fix it, if so I'll add a new comment.

**Comment by WorldTeacher** [comment]
Reboot seems to have fixed that, download speed is also way faster than before
