### ISSUE TITLE
Update domain for hentaichan.live

### ISSUE THREAD

**Issue by Couch0wl** [HDoujinDownloader/HDoujinDownloader#128]
hentaichan.live changed address: https://y.hentaichan.live
Authorization also no longer works.

**Comment by HDoujinDownloader** [comment]
The domain has now been updated with d9dfdb58e1d60e4a5dfed4952fe98e6506db6eff.

Updating the domain should also get the login working, too. It seems to be working from my end, but let me know if you encounter any further problems.
