### ISSUE TITLE
hbrowse.com seems to be broken

### ISSUE THREAD

**Issue by vorpalhex** [HDoujinDownloader/HDoujinDownloader#137]
Currently downloads from hbrowse don't seem to work, despite it being listed in the supported sites and entries appearing to work.

Downloads go to "Completed" status, but Progress reports 0/0 and File Size comes back as 0 B. No files are created on disk. Logs don't report anything useful other than "saving repository metadata". 

Other sites work as expected.

**Comment by HDoujinDownloader** [comment]
This site's been around for a long time! It's a really nostalgic one for me; it was one of the first I added to HDoujin Downloader years ago.

I just uploaded a fix, so it should be working the next time you restart HDoujin Downloader!
