### ISSUE TITLE
koushoku.org: Fix missing metadata

### ISSUE THREAD

**Issue by namekman** [HDoujinDownloader/HDoujinDownloader#138]
Artist and Tags are not being imported from Koushoku with the current Koushoku.lua (which got encoded for some reasons)
For the current DOM, GetInfo should probably be like this :
````
function GetInfo()
    if(IsTagUrl()) then
        EnqueueAllGalleries()
    else
        info.Title = dom.SelectValue('//h1')
        info.Artist = dom.SelectValues('//a[contains(@href,"/artists/")]')
        info.Tags = dom.SelectValues('//div[contains(@class,"tags")]//a')
    end
end
````

**Comment by HDoujinDownloader** [comment]
This has now been resolved with f0c97aacc15c4d89c8bef9d7cd364f5e734d2421, but now images aren't able to be downloaded. This issue will be tracked in #145.
