### ISSUE TITLE
Error downloading from bilibilicomics.com

### ISSUE THREAD

**Issue by ghost** [HDoujinDownloader/HDoujinDownloader#140]
I tried downloading paid comics (that I paid for) from [Bilibilicomics](https://www.bilibilicomics.com) using [your guide](https://github.com/HDoujinDownloader/HDoujinDownloader/wiki/Getting-Bearer-Token-From-Web-Browser), but I could not. Only the starting two images are being downloaded.

For free chapters, all images are being downloaded, but for paid chapters only the starting two images are being downloaded even if I use the bearer token.

Can you check it, if possible site login for [bilibili](https://www.bilibilicomics.com) in hdoujindownloader would be appreciated.

**Comment by HDoujinDownloader** [comment]
You're right, only the first two images are accessible by the API for episodes that aren't unlocked. Some episodes can be accessed for free by waiting a certain amount of time to unlock them, after which they remain accessible when signed in to your account.

To access the images for a given episode, we need to make an API request to `/twirp/comic.v1.Comic/GetImageIndex`, which returns a JSON object containing an array of images. We do this by posting a JSON payload to the API endpoint, which looks like `{"ep_id":00000,"credential":""}`.

For free episodes, the `credential` field can be left blank. But for unlocked episodes tied to your account, we need the `credential` value to access more than two images. To get this value, we need to make a request to `/twirp/global.v1.Comic/GetCredential` first.

I've implemented this process in cf63c10, but the API complaints that the `credential` value is invalid. I need to investigate further to figure out why.

I'll continue discussing this issue in #85 as it pertains to account authentication.
