### ISSUE TITLE
error adding new download for nhentai.net

### ISSUE THREAD

**Issue by hamkah2c** [HDoujinDownloader/HDoujinDownloader#142]
expected result : the manga title is show up
the result : only show nhentai.net text
log and image attached
![image](https://user-images.githubusercontent.com/8862875/187035902-2f7b7dd0-7e19-40ea-b7e4-efef00c4a3c5.png)
[1661611423-nhentai.net.log](https://github.com/HDoujinDownloader/HDoujinDownloader/files/9438177/1661611423-nhentai.net.log)

**Comment by HDoujinDownloader** [comment]
Thanks a lot for including the log file; it's always helpful! 

I'm closing this issue as a duplicate of #144, but you can see my response there!
