### ISSUE TITLE
hitomi.la: not working

### ISSUE THREAD

**Issue by ghost4239** [HDoujinDownloader/HDoujinDownloader#149]
not download from hitomi.la

20:13:27 hdoujin dow [i] CLR Version: 4.0.30319.42000
20:13:27 hdoujin dow [i] Framework Version: 4.8.4515.0
20:13:27 hdoujin dow [i] OS Version: Microsoft Windows NT 6.2.9200.0 (64-bit)
20:13:27 hdoujin dow [i] Locale: en-ES
20:13:27 hdoujin dow [i] Path: Personal\HDoujin.Downloader-2021.10.12.0-win\HDoujin Downloader.exe
20:13:27 hdoujin dow [i] Working Directory: Personal\HDoujin.Downloader-2021.10.12.0-win
20:13:27 hdoujin dow [i] Timestamp: 09-17-2022 8:12:55
20:13:27 hdoujin dow [i] Product Version: 2022.1.3
20:13:27 hdoujin dow [i] Available Security Protocols: SSL 3.0, TLS 1.0, TLS 1.1, TLS 1.2, TLS 1.3
20:13:27 hdoujin dow [i] Standalone: False
20:13:27 hdoujin dow [i] Repositories: Official Lua Repository, Internal
20:13:27 hdoujin dow [i] Theme: Default
20:13:27 page grabbe [x] ReferenceError: navigator is not defined

![imagen](https://user-images.githubusercontent.com/33614437/190879318-8bafe0a4-d9a0-4942-97f9-66e7b60f24a8.png)

**Comment by HDoujinDownloader** [comment]
It should be fixed now with d86db985de3355a921e6126be568457cbf9e011d!
