### ISSUE TITLE
Unable to access full version features after purchase 

### ISSUE THREAD

**Issue by itschrisonline** [HDoujinDownloader/HDoujinDownloader#161]
Hi after trying to update with modules, it fails.
I have check permissions. This is the error I keep getting
![fullversionerror](https://user-images.githubusercontent.com/13555496/201499206-24055c88-c27a-469b-9720-de8f4e2d53ee.PNG)

**Comment by HDoujinDownloader** [comment]
This is a known issue with the latest release-- See #75 for a workaround in the meantime!
