### ISSUE TITLE
reaperscans.com: Chapter list is incomplete

### ISSUE THREAD

**Issue by HDoujinDownloader** [HDoujinDownloader/HDoujinDownloader#180]
The chapter list is paginated for some manga, and HDoujin Downloader struggles to get chapters beyond a certain depth. This is because requests for deeper pages (5+) return an empty chapter list. It doesn't seem to be a referer issue, and the behavior can be reproduced in the web browser by opening and refreshing one of the pages.

A workaround could be fetching chapters through their API instead (`/livewire/message/frontend.novel-chapters-list`).

**Comment by mrstan3772** [comment]
> The chapter list is paginated for some manga, and HDoujin Downloader struggles to get chapters beyond a certain depth. This is because requests for deeper pages (5+) return an empty chapter list. It doesn't seem to be a referer issue, and the behavior can be reproduced in the web browser by opening and refreshing one of the pages.
> 
> A workaround could be fetching chapters through their API instead (`/livewire/message/frontend.novel-chapters-list`).



_I added a patch to fix misleading page fetching on my local module but i can't fix chapter pagination error_ 

### Code :

`
function GetChapters()

    local maxPageIndex = dom.SelectElements('//span[contains(@*,"paginator-page")]').Count()

    if(maxPageIndex <= 0) then
        maxPageIndex = 1
    end

    for currentPageIndex = 1, maxPageIndex do

        http.Referer = url

        url = SetParameter(url, 'page', currentPageIndex)
        dom = Dom.New(http.Get(url))

        local chapterNodes = dom.SelectElements('(//ul[@role="list"])[1]//a[contains(@href,"/chapters/")]')

        for i = 0, chapterNodes.Count() - 1 do

            local chapterNode = chapterNodes[i]
            local chapter = ChapterInfo.New()

            chapter.Url = chapterNode.SelectValue('./@href')
            chapter.Title = chapterNode.SelectValue('.//p')
            
            chapters.Add(chapter)

        end

        sleep(10)

    end

    chapters.Reverse()

end

function GetPages()

    pages.AddRange(dom.SelectValues('//main//img[contains(@src,"media.reaperscans.com") or contains(@class,"max-w-full mx-auto display-block")]/@src'))

end

function sleep(s)
    local ntime = os.clock() + s/10
    repeat until os.clock() > ntime
end
`

**Comment by mrstan3772** [comment]
Is possible to execute JS on DOM page context to simulate a click and get chapter list or simulate emit event on specific action to change chapter ?

**Comment by HDoujinDownloader** [comment]
> Is possible to execute JS on DOM page context to simulate a click and get chapter list or simulate emit event on specific action to change chapter list ?

There's no way to do that right now, but there is a web driver API available in the Lua API that I could add this functionality to. In most cases this can be done more efficiently by recreating the API requests associated with the action though.

In any case, I'm going to move further discussion of this issue to #223, as this site needs more than just chapter list fixes now.
