### ISSUE TITLE
titles from mangago.me not downloading

### ISSUE THREAD

**Issue by LadyHaywood** [HDoujinDownloader/HDoujinDownloader#197]
I tried downloading from mangago.me and it wouldn't start. I did check to see if it was supported because I know some programs like these don't do to how the site works. Was glad to see that it is on the list but also saw the comment saying it may take awhile to actually add. So I'm not sure if it is actually supported yet.

**Comment by HDoujinDownloader** [comment]
Wew, it's over a year later, but Mangago should be working now as of 
e23401d.
