### ISSUE TITLE
Fix download for bato.to

### ISSUE THREAD

**Issue by LadyHaywood** [HDoujinDownloader/HDoujinDownloader#198]
I know I just made a post about mangago.me and I'm sorry for double posting so soon. But I went to tried bato.to as a substitute and it worked fine for one book and then every book after that came back with  a page collection error.

**Comment by HDoujinDownloader** [comment]
Don't worry, it's okay! 

I noticed that the "v2x" version of the site is still working, while "v3x" is not.

Could you give me an example URL that's not working so I can make sure I'm on the right track with this?

**Comment by LadyHaywood** [comment]
Honestly, that does make sense to me since I think the 1st book I downloaded was on the v2 site but then I switched over to v3 because I like that interface better. I didn't even think about that.

This is the book I'm currently trying to download https://bato.to/title/23422-hourou-musuko

**Comment by HDoujinDownloader** [comment]
You should be able to download from both versions of the website now!
