### ISSUE TITLE
Kuroneko Reader/Manga Database Download Fails

### ISSUE THREAD

**Issue by adgrant93** [HDoujinDownloader/HDoujinDownloader#201]
I have tried this on multiple machines and receive the same result. I go to help > download > check for updates and the update does not download. It fails saying it may not have write permissions to the directory. This dir is in my local user downloads folder. I have tried running as admin but no change unfortunately. I checked event viewer for logs but did not see anything. Is this a known issue?

Thanks

![image](https://user-images.githubusercontent.com/36750334/236466724-6af74d4e-2d1c-44ec-be62-ae491a5d6591.png)

**Comment by HDoujinDownloader** [comment]
This is indeed a known issue. It's a problem with the updater being unable to download the archive containing the additional modules right now. 

However, you can still download them manually by following the workaround given here: https://github.com/HDoujinDownloader/HDoujinDownloader/issues/75

**Comment by adgrant93** [comment]
Thanks.
