### ISSUE TITLE
wings.sbs not downloading any images

### ISSUE THREAD

**Issue by Fallen98** [HDoujinDownloader/HDoujinDownloader#205]
While it goes through the chapters, and it shows the right amount of pages while downloading it seems it's not downloading any images

**Comment by HDoujinDownloader** [comment]
This is my bad-- I forgot to publish a new pre-release with updates required for this site to work properly.

Please update to the latest pre-release [here](https://github.com/HDoujinDownloader/HDoujinDownloader/releases/download/v2023.5.6.0-rc.7/HDoujin.Downloader-2023.5.6.0-rc.7-win.zip), and then the site should be working fine!

**Comment by Fallen98** [comment]
> This is my bad-- I forgot to publish a new pre-release with updates required for this site to work properly.
> 
> Please update to the latest pre-release [here](https://github.com/HDoujinDownloader/HDoujinDownloader/releases/download/v2023.5.6.0-rc.7/HDoujin.Downloader-2023.5.6.0-rc.7-win.zip), and then the site should be working fine!

Thanks, that fixed it
