### ISSUE TITLE
nhentai.uk not downloading pics

### ISSUE THREAD

**Issue by MimoKar** [HDoujinDownloader/HDoujinDownloader#210]
Hi,

the gallery from nhentai.uk is added properly, but separated pictures can't be downloaded.
In log, I see error 520.
I have login and I populated it to application too.

**Comment by HDoujinDownloader** [comment]
It seems to be working fine from my end, could you send me an example gallery with this problem?

You could try disabling your login, because I haven't tested it with this site. The only nhentai site I've officially tested it with is the OG (nhentai.net).

**Comment by MimoKar** [comment]
Hi, yes, in latest HD it is working fine even with the login. But is it possible to use pretty titles, as for example used in nhentai.net ?

**Comment by HDoujinDownloader** [comment]
Yes! Now it is. Just enable the same setting as you would use for nhentai.net, and it'll work for this site too.
