### ISSUE TITLE
Unable to download from toongod.org

### ISSUE THREAD

**Issue by Casshernsins** [HDoujinDownloader/HDoujinDownloader#215]
The download disappears when prompted to start.

**Comment by HDoujinDownloader** [comment]
I just uploaded a fix for this site, so the metadata and chapters should all show up correctly now.

The only thing that images hosted on their CDN (cdn.toongod.org) don't seem to be downloading, and requests to them are immediately blocked by Cloudflare. Chapters with images hosted on other domains will download normally. I'm not totally sure why this is, and need to investigate further.

**Comment by Casshernsins** [comment]
Thank you! Hope you'll find what's wrong.

**Comment by HDoujinDownloader** [comment]
I did! This has now been resolved in the latest pre-release, which you can download [here](https://github.com/HDoujinDownloader/HDoujinDownloader/releases/download/v2023.6.13.0-rc.9/HDoujin.Downloader-2023.6.13.0-rc.9-win.zip).

Let me know if you run into any problems!

**Comment by Casshernsins** [comment]
Amazing! Thanks :D
