### ISSUE TITLE
lezhinus images scrambled

### ISSUE THREAD

**Issue by hikarijxs** [HDoujinDownloader/HDoujinDownloader#232]
can you please look into lezhinus, they've added protections that make the downloads unreadable. 

downloaded chapters come out like this now.

![1](https://github.com/HDoujinDownloader/HDoujinDownloader/assets/139346223/9d86d867-bbe8-42f5-adb9-84e9a8d90492)

**Comment by GorgoIlCane** [comment]
came here to report the same, though it's not for every series (yet).

it goes for free and paid chapters, here is an example: https://www.lezhinus.com/en/comic/left_unwritten

**Comment by mrstan3772** [comment]
> came here to report the same, though it's not for every series (yet).
> 
> it goes for free and paid chapters, here is an example: https://www.lezhinus.com/en/comic/left_unwritten

Have you tried with the latest version : https://github.com/HDoujinDownloader/HDoujinDownloader/releases/tag/v2023.9.19.0
