### ISSUE TITLE
Error when using nhentai

### ISSUE THREAD

**Issue by malokoko** [HDoujinDownloader/HDoujinDownloader#239]
Since the last update of FlareSolverr I can't add anything from nhentai anymore. I downloaded the latest version of HDoujin but it doesn't work. Before this, the program worked for me, so I don't know if I'm doing something wrong.

Here is the information I got from the log.

`00:37:12 hdoujinchal [x] System.Net.WebException: The challenge solver threw an exception. ---> DXHiYiCFsWLYiGtMRkDssZlbXsbK: Failed to execute FlareSolverr command. ---> System.Net.WebException: Anulada la solicitud: Se excedió el tiempo de espera de la operación.
   en System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   en System.Net.WebClient.UploadString(Uri address, String method, String data)
   en DwgBchgvSlknyORehtgKhuQzctVT.Gsemac.Net.IWebClient.UploadString(Uri address, String data)
   en zDIIuPnIyJXvjMQNYQhTchlxbISH.TnODtoGIoLVGXoemKhtlcWigZyjoB(maFfkFHnzPedhKoNBkrxvHRwbqfF , Boolean , Boolean )
   en lOpKMkSgmHdFwPyDKoIGHNyuBWRm.MPLjgXDRNGbuAFkIcbdKBpAXppDK(cQghsbBmJwOifKUHVVeYBSbysHkt , Exception , CancellationToken )
   --- Fin del seguimiento de la pila de la excepción interna ---
   en lOpKMkSgmHdFwPyDKoIGHNyuBWRm.MPLjgXDRNGbuAFkIcbdKBpAXppDK(cQghsbBmJwOifKUHVVeYBSbysHkt , Exception , CancellationToken )
   en uEoQLunNnkpSkbTIhjHctKEuIMdP.YKYCkzYeUcIqpZLRLdVcHfdvGagT.JAqtdNsWGjlTajrEFYhWyAZFSOhL(cQghsbBmJwOifKUHVVeYBSbysHkt )
   en iegAxWjulwXDFXGhDcrogKTuNuDl.TnODtoGIoLVGXoemKhtlcWigZyjoB()
   en KplTcnmMJuCJDCFJYPOrMQJAgscYA.EzXjAfPSynKqsEUIqExlbhtNgjwT(WebRequest , CancellationToken )
   en KItzTFbuykPvlDHTOkMelegqjpEI.EzXjAfPSynKqsEUIqExlbhtNgjwT(WebRequest , CancellationToken )
   en egGnngPCQZHfUOXROjxUeUrPLlqn.EzXjAfPSynKqsEUIqExlbhtNgjwT(cQghsbBmJwOifKUHVVeYBSbysHkt , CancellationToken )
   en uEoQLunNnkpSkbTIhjHctKEuIMdP.EzXjAfPSynKqsEUIqExlbhtNgjwT(cQghsbBmJwOifKUHVVeYBSbysHkt , CancellationToken )
   --- Fin del seguimiento de la pila de la excepción interna ---
   en uEoQLunNnkpSkbTIhjHctKEuIMdP.EzXjAfPSynKqsEUIqExlbhtNgjwT(cQghsbBmJwOifKUHVVeYBSbysHkt , CancellationToken )
   en egGnngPCQZHfUOXROjxUeUrPLlqn.EzXjAfPSynKqsEUIqExlbhtNgjwT(WebRequest , CancellationToken )
   en KItzTFbuykPvlDHTOkMelegqjpEI.EzXjAfPSynKqsEUIqExlbhtNgjwT(WebRequest , CancellationToken )
   en PUgSntBBwqzcedNGJqFRPLVphcKq.MPLjgXDRNGbuAFkIcbdKBpAXppDK(cQghsbBmJwOifKUHVVeYBSbysHkt , Exception , CancellationToken )
00:37:12 http        [x] Exception was thrown when accessing https://nhentai.net/g/470025/: System.Net.WebException: The challenge solver threw an exception. ---> System.Net.WebException: The challenge solver threw an exception. ---> DXHiYiCFsWLYiGtMRkDssZlbXsbK: Failed to execute FlareSolverr command. ---> System.Net.WebException: Anulada la solicitud: Se excedió el tiempo de espera de la operación.
   en System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   en System.Net.WebClient.UploadString(Uri address, String method, String data)
   en DwgBchgvSlknyORehtgKhuQzctVT.Gsemac.Net.IWebClient.UploadString(Uri address, String data)
   en zDIIuPnIyJXvjMQNYQhTchlxbISH.TnODtoGIoLVGXoemKhtlcWigZyjoB(maFfkFHnzPedhKoNBkrxvHRwbqfF , Boolean , Boolean )
   en lOpKMkSgmHdFwPyDKoIGHNyuBWRm.MPLjgXDRNGbuAFkIcbdKBpAXppDK(cQghsbBmJwOifKUHVVeYBSbysHkt , Exception , CancellationToken )
   --- Fin del seguimiento de la pila de la excepción interna ---
   en lOpKMkSgmHdFwPyDKoIGHNyuBWRm.MPLjgXDRNGbuAFkIcbdKBpAXppDK(cQghsbBmJwOifKUHVVeYBSbysHkt , Exception , CancellationToken )
   en uEoQLunNnkpSkbTIhjHctKEuIMdP.YKYCkzYeUcIqpZLRLdVcHfdvGagT.JAqtdNsWGjlTajrEFYhWyAZFSOhL(cQghsbBmJwOifKUHVVeYBSbysHkt )
   en iegAxWjulwXDFXGhDcrogKTuNuDl.TnODtoGIoLVGXoemKhtlcWigZyjoB()
   en KplTcnmMJuCJDCFJYPOrMQJAgscYA.EzXjAfPSynKqsEUIqExlbhtNgjwT(WebRequest , CancellationToken )
   en KItzTFbuykPvlDHTOkMelegqjpEI.EzXjAfPSynKqsEUIqExlbhtNgjwT(WebRequest , CancellationToken )
   en egGnngPCQZHfUOXROjxUeUrPLlqn.EzXjAfPSynKqsEUIqExlbhtNgjwT(cQghsbBmJwOifKUHVVeYBSbysHkt , CancellationToken )
   en uEoQLunNnkpSkbTIhjHctKEuIMdP.EzXjAfPSynKqsEUIqExlbhtNgjwT(cQghsbBmJwOifKUHVVeYBSbysHkt , CancellationToken )
   --- Fin del seguimiento de la pila de la excepción interna ---
   en uEoQLunNnkpSkbTIhjHctKEuIMdP.EzXjAfPSynKqsEUIqExlbhtNgjwT(cQghsbBmJwOifKUHVVeYBSbysHkt , CancellationToken )
   en egGnngPCQZHfUOXROjxUeUrPLlqn.EzXjAfPSynKqsEUIqExlbhtNgjwT(WebRequest , CancellationToken )
   en KItzTFbuykPvlDHTOkMelegqjpEI.EzXjAfPSynKqsEUIqExlbhtNgjwT(WebRequest , CancellationToken )
   en PUgSntBBwqzcedNGJqFRPLVphcKq.MPLjgXDRNGbuAFkIcbdKBpAXppDK(cQghsbBmJwOifKUHVVeYBSbysHkt , Exception , CancellationToken )
   en uEoQLunNnkpSkbTIhjHctKEuIMdP.YKYCkzYeUcIqpZLRLdVcHfdvGagT.JAqtdNsWGjlTajrEFYhWyAZFSOhL(cQghsbBmJwOifKUHVVeYBSbysHkt )
   en iegAxWjulwXDFXGhDcrogKTuNuDl.TnODtoGIoLVGXoemKhtlcWigZyjoB()
   en KplTcnmMJuCJDCFJYPOrMQJAgscYA.EzXjAfPSynKqsEUIqExlbhtNgjwT(WebRequest , CancellationToken )
   en KItzTFbuykPvlDHTOkMelegqjpEI.EzXjAfPSynKqsEUIqExlbhtNgjwT(WebRequest , CancellationToken )
   en egGnngPCQZHfUOXROjxUeUrPLlqn.EzXjAfPSynKqsEUIqExlbhtNgjwT(cQghsbBmJwOifKUHVVeYBSbysHkt , CancellationToken )
   en PsugiLqRoeDQnKfXWLIXGYZavIRIA.EzXjAfPSynKqsEUIqExlbhtNgjwT(cQghsbBmJwOifKUHVVeYBSbysHkt , CancellationToken )
   en egGnngPCQZHfUOXROjxUeUrPLlqn.EzXjAfPSynKqsEUIqExlbhtNgjwT(WebRequest , CancellationToken )
   en KItzTFbuykPvlDHTOkMelegqjpEI.EzXjAfPSynKqsEUIqExlbhtNgjwT(WebRequest , CancellationToken )
   en egGnngPCQZHfUOXROjxUeUrPLlqn.EzXjAfPSynKqsEUIqExlbhtNgjwT(cQghsbBmJwOifKUHVVeYBSbysHkt , CancellationToken )
   en HeoUskkGXtFtzSNHatmHwHiQknHL.EzXjAfPSynKqsEUIqExlbhtNgjwT(cQghsbBmJwOifKUHVVeYBSbysHkt , CancellationToken )
   en egGnngPCQZHfUOXROjxUeUrPLlqn.EzXjAfPSynKqsEUIqExlbhtNgjwT(WebRequest , CancellationToken )
   en KItzTFbuykPvlDHTOkMelegqjpEI.EzXjAfPSynKqsEUIqExlbhtNgjwT(WebRequest , CancellationToken )
   en BfTzJlxfMhVQaakCjWusVSNvdKpU.EzXjAfPSynKqsEUIqExlbhtNgjwT(WebRequest , CancellationToken )
   en KItzTFbuykPvlDHTOkMelegqjpEI.EzXjAfPSynKqsEUIqExlbhtNgjwT(WebRequest , CancellationToken )
   en egGnngPCQZHfUOXROjxUeUrPLlqn.EzXjAfPSynKqsEUIqExlbhtNgjwT(cQghsbBmJwOifKUHVVeYBSbysHkt , CancellationToken )
   en PcpSyQaHmIdpMhgVRjMULOXQzeOT.EzXjAfPSynKqsEUIqExlbhtNgjwT(cQghsbBmJwOifKUHVVeYBSbysHkt , CancellationToken )
   en egGnngPCQZHfUOXROjxUeUrPLlqn.EzXjAfPSynKqsEUIqExlbhtNgjwT(WebRequest , CancellationToken )
   en KItzTFbuykPvlDHTOkMelegqjpEI.EzXjAfPSynKqsEUIqExlbhtNgjwT(WebRequest , CancellationToken )
   en egGnngPCQZHfUOXROjxUeUrPLlqn.EzXjAfPSynKqsEUIqExlbhtNgjwT(cQghsbBmJwOifKUHVVeYBSbysHkt , CancellationToken )
   en yIYexnuMscTXgvUBdjvyFkHXObtA.EzXjAfPSynKqsEUIqExlbhtNgjwT(cQghsbBmJwOifKUHVVeYBSbysHkt , CancellationToken )
   en egGnngPCQZHfUOXROjxUeUrPLlqn.EzXjAfPSynKqsEUIqExlbhtNgjwT(WebRequest , CancellationToken )
   en KItzTFbuykPvlDHTOkMelegqjpEI.EzXjAfPSynKqsEUIqExlbhtNgjwT(WebRequest , CancellationToken )
   en egGnngPCQZHfUOXROjxUeUrPLlqn.EzXjAfPSynKqsEUIqExlbhtNgjwT(cQghsbBmJwOifKUHVVeYBSbysHkt , CancellationToken )
   en uEoQLunNnkpSkbTIhjHctKEuIMdP.EzXjAfPSynKqsEUIqExlbhtNgjwT(cQghsbBmJwOifKUHVVeYBSbysHkt , CancellationToken )
   --- Fin del seguimiento de la pila de la excepción interna ---
   en uEoQLunNnkpSkbTIhjHctKEuIMdP.EzXjAfPSynKqsEUIqExlbhtNgjwT(cQghsbBmJwOifKUHVVeYBSbysHkt , CancellationToken )
   en egGnngPCQZHfUOXROjxUeUrPLlqn.EzXjAfPSynKqsEUIqExlbhtNgjwT(WebRequest , CancellationToken )
   en KItzTFbuykPvlDHTOkMelegqjpEI.EzXjAfPSynKqsEUIqExlbhtNgjwT(WebRequest , CancellationToken )
   en egGnngPCQZHfUOXROjxUeUrPLlqn.EzXjAfPSynKqsEUIqExlbhtNgjwT(cQghsbBmJwOifKUHVVeYBSbysHkt , CancellationToken )
   en JBJeiRbjwiBGHJTSNqhkinMhTwtkc.EzXjAfPSynKqsEUIqExlbhtNgjwT(cQghsbBmJwOifKUHVVeYBSbysHkt , CancellationToken )
   en egGnngPCQZHfUOXROjxUeUrPLlqn.EzXjAfPSynKqsEUIqExlbhtNgjwT(WebRequest , CancellationToken )
   en KItzTFbuykPvlDHTOkMelegqjpEI.EzXjAfPSynKqsEUIqExlbhtNgjwT(WebRequest , CancellationToken )
   en lwygcqlYCJioJuwYMrgUTgaRHfVS.NDfulIJMDLsoJUqxGeFeDgdWvqMg(String , CookieContainer , String[] , String , VpyDdHTVnQVQsYeEjscdxgrQByOR , String[] )
00:37:12 flaresolver [x] Error: Error solving the challenge. Timeout after 100.0 seconds.
00:37:12 flaresolver [i] Response in 100.123 s
00:37:12 flaresolver [i] 127.0.0.1 POST http://localhost:8191/v1 500 Internal Server Error
00:37:12 info grabbe [i] Got info for https://nhentai.net/g/470025/ using nhentai module
00:37:12 queue       [!] Skipped https://nhentai.net/g/470025/ (Invalid response or missing/outdated module)
`

**Comment by HDoujinDownloader** [comment]
> ```Error: Error solving the challenge. Timeout after 100.0 seconds.```

FlareSolverr is timing out while trying to solve the Cloudflare challenge. 

Do you know exactly what version of FlareSolverr you're using? If you open the logger by going to **_Tools > Log Viewer_**, it will show the FlareSolverr version when it starts up for the first time.

Try downloading the latest version (3.3.2) from [here](https://github.com/FlareSolverr/FlareSolverr/releases/download/v3.3.2/flaresolverr_windows_x64.zip) and plopping it into your `plugins` folder. I recommend deleting all other versions of the plugin that may be present in case it's trying to use an older one.

**Comment by malokoko** [comment]
> > `Error: Error solving the challenge. Timeout after 100.0 seconds.`
> 
> FlareSolverr is timing out while trying to solve the Cloudflare challenge.
> 
> Do you know exactly what version of FlareSolverr you're using? If you open the logger by going to **_Tools > Log Viewer_**, it will show the FlareSolverr version when it starts up for the first time.
> 
> Try downloading the latest version (3.3.2) from [here](https://github.com/FlareSolverr/FlareSolverr/releases/download/v3.3.2/flaresolverr_windows_x64.zip) and plopping it into your `plugins` folder. I recommend deleting all other versions of the plugin that may be present in case it's trying to use an older one.

I have also downloaded the latest version of HDoujin but still getting the same error.

> (00:36:27 hdoujin dow [i] Timestamp: 29/08/2023 0:33:52
> 00:36:27 hdoujin dow [i] Product Version: 2023.8.28-2
> 00:36:27 hdoujin dow [i] Available Security Protocols: SSL 3.0, TLS 1.0, TLS 1.1, TLS 1.2
> 00:36:27 hdoujin dow [i] Standalone: False
> 00:36:27 hdoujin dow [i] Repositories: Official Lua Repository, Internal
> 00:36:27 hdoujin dow [i] Theme: Default
> 00:36:27 queue       [i] Attempting to enqueue https://nhentai.net/g/470025/
> 00:36:27 hdoujinchal [i] Using FlareSolverrChallengeHandler
> 00:36:27 flaresolver [i] Starting FlareSolverr service
> 00:36:27 flaresolver [i] Starting FlareSolverr process
> 00:36:27 flaresolver [i] FlareSolverr 3.3.2
> 00:36:27 flaresolver [i] Testing web browser installation...
> 00:36:27 flaresolver [i] Platform: Windows-10-10.0.19045-SP0
> 00:36:27 flaresolver [i] Chrome / Chromium path: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> 00:36:27 flaresolver [i] Chrome / Chromium major version: 116
> 00:36:27 flaresolver [i] Launching web browser...
> 00:36:27 queue       [i] Attempting to enqueue https://nhentai.net/g/469814/
> 00:36:27 queue       [i] Attempting to enqueue https://nhentai.net/g/470093/
> 00:36:27 flaresolver [i] FlareSolverr User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
> 00:36:27 flaresolver [i] Test successful!
> 00:36:27 flaresolver [i] Serving on http://0.0.0.0:8191
> 00:36:27 flaresolver [i] FlareSolverr is now listening on port 8191
> 00:36:27 flaresolver [i] Creating a new session
> 00:36:27 flaresolver [i] Incoming request => POST /v1 body: {'cmd': 'sessions.create', 'download': False, 'maxTimeout': 60000, 'headers': {}, 'cookies': [], 'returnOnlyCookies': False}
> 00:36:27 flaresolver [!] Request parameter 'headers' was removed in FlareSolverr v2.
> 00:36:27 flaresolver [i] Response in 1.289 s
> 00:36:27 flaresolver [i] 127.0.0.1 POST http://localhost:8191/v1 200 OK
> 00:36:27 flaresolver [i] Created session with ID 01445662-45f3-11ee-96e6-001a7dda7115
> 00:36:27 flaresolver [i] Incoming request => POST /v1 body: {'cmd': 'request.get', 'download': True, 'url': 'https://nhentai.net/g/470025/', 'maxTimeout': 100000, 'headers': {'Accept-Language': 'en-US,en;q=0.5', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'Keep-Alive'}, 'cookies': [], 'session': '01445662-45f3-11ee-96e6-001a7dda7115', 'returnOnlyCookies': False}
> 00:36:27 flaresolver [!] Request parameter 'headers' was removed in FlareSolverr v2.
> 00:36:27 flaresolver [!] Request parameter 'download' was removed in FlareSolverr v2.
> 00:36:27 flaresolver [i] Challenge detected. Selector found: #challenge-spinner)
> 00:36:27 official lu [i] Saving metadata cache
> 00:36:27 official lu [i] Reading metadata cache from modules\Lua\metadata.json
> 00:36:27 official lu [i] Saving metadata cache
> 00:36:27 repositorie [i] Finished synchronizing repository "Official Lua Repository"
> 00:36:27 repositorie [i] Finished synchronizing repositories
> 00:36:27 hdoujinchal [x] System.Net.WebException: The challenge solver threw an exception. ---> YTJkZNrhxtTGmVNlVILabjdFOiwy: Failed to execute FlareSolverr command. ---> System.Net.WebException: Anulada la solicitud: Se excedió el tiempo de espera de la operación.
>    en System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
>    en System.Net.WebClient.UploadString(Uri address, String method, String data)
>    en KMupJOVYJKwuoLKHdkNGqAKBvYCt.Gsemac.Net.IWebClient.UploadString(Uri address, String data)
>    en gSYZloKkloEUvGXuGWnLprnVlGBfA.YyWGKXxHvsJQJnGZUSfzTOovPuyj(jMXkCieOciRrlJCeBoTtgcLIqSwy , Boolean , Boolean )
>    en cgzqzRxwdmPYkYZgUppMOAqQtCYl.JhJIOcekAxMkISEhsyEAGWCrQUYo(zIoJbUcUEBbblFwoZJzUEObOoOvF , Exception , CancellationToken )
>    --- Fin del seguimiento de la pila de la excepción interna ---
>    en cgzqzRxwdmPYkYZgUppMOAqQtCYl.JhJIOcekAxMkISEhsyEAGWCrQUYo(zIoJbUcUEBbblFwoZJzUEObOoOvF , Exception , CancellationToken )
>    en rsyoJPQXiPBckwmpxiaucBIICdkO.ncbYKqesqnWGQoHnZSgbXqqbEhvd.CKmCIghBLCzgeMkhFQbIfSZpCfoY(zIoJbUcUEBbblFwoZJzUEObOoOvF )
>    en zPsEjbKYyPRCPCLITmWwvwJGFoSo.YyWGKXxHvsJQJnGZUSfzTOovPuyj()
>    en NffZeQBAlZOdFYmEApVjBBDuPypC.RHFhpAmqlOntwPilgxChauxjAdfj(WebRequest , CancellationToken )
>    en LeviEkEknBnAjEleOrDwkhyWgKPt.RHFhpAmqlOntwPilgxChauxjAdfj(WebRequest , CancellationToken )
>    en xxYoKTgHZoikGDMaKgOGehbpCAnpA.RHFhpAmqlOntwPilgxChauxjAdfj(zIoJbUcUEBbblFwoZJzUEObOoOvF , CancellationToken )
>    en rsyoJPQXiPBckwmpxiaucBIICdkO.RHFhpAmqlOntwPilgxChauxjAdfj(zIoJbUcUEBbblFwoZJzUEObOoOvF , CancellationToken )
>    --- Fin del seguimiento de la pila de la excepción interna ---
>    en rsyoJPQXiPBckwmpxiaucBIICdkO.RHFhpAmqlOntwPilgxChauxjAdfj(zIoJbUcUEBbblFwoZJzUEObOoOvF , CancellationToken )
>    en xxYoKTgHZoikGDMaKgOGehbpCAnpA.RHFhpAmqlOntwPilgxChauxjAdfj(WebRequest , CancellationToken )
>    en LeviEkEknBnAjEleOrDwkhyWgKPt.RHFhpAmqlOntwPilgxChauxjAdfj(WebRequest , CancellationToken )
>    en KbsAgUuvORdKoqrCVctFQLBBVLDd.JhJIOcekAxMkISEhsyEAGWCrQUYo(zIoJbUcUEBbblFwoZJzUEObOoOvF , Exception , CancellationToken )
> 00:36:27 http        [x] Exception was thrown when accessing https://nhentai.net/g/470025/: System.Net.WebException: The challenge solver threw an exception. ---> System.Net.WebException: The challenge solver threw an exception. ---> YTJkZNrhxtTGmVNlVILabjdFOiwy: Failed to execute FlareSolverr command. ---> System.Net.WebException: Anulada la solicitud: Se excedió el tiempo de espera de la operación.
>    en System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
>    en System.Net.WebClient.UploadString(Uri address, String method, String data)
>    en KMupJOVYJKwuoLKHdkNGqAKBvYCt.Gsemac.Net.IWebClient.UploadString(Uri address, String data)
>    en gSYZloKkloEUvGXuGWnLprnVlGBfA.YyWGKXxHvsJQJnGZUSfzTOovPuyj(jMXkCieOciRrlJCeBoTtgcLIqSwy , Boolean , Boolean )
>    en cgzqzRxwdmPYkYZgUppMOAqQtCYl.JhJIOcekAxMkISEhsyEAGWCrQUYo(zIoJbUcUEBbblFwoZJzUEObOoOvF , Exception , CancellationToken )
>    --- Fin del seguimiento de la pila de la excepción interna ---
>    en cgzqzRxwdmPYkYZgUppMOAqQtCYl.JhJIOcekAxMkISEhsyEAGWCrQUYo(zIoJbUcUEBbblFwoZJzUEObOoOvF , Exception , CancellationToken )
>    en rsyoJPQXiPBckwmpxiaucBIICdkO.ncbYKqesqnWGQoHnZSgbXqqbEhvd.CKmCIghBLCzgeMkhFQbIfSZpCfoY(zIoJbUcUEBbblFwoZJzUEObOoOvF )
>    en zPsEjbKYyPRCPCLITmWwvwJGFoSo.YyWGKXxHvsJQJnGZUSfzTOovPuyj()
>    en NffZeQBAlZOdFYmEApVjBBDuPypC.RHFhpAmqlOntwPilgxChauxjAdfj(WebRequest , CancellationToken )
>    en LeviEkEknBnAjEleOrDwkhyWgKPt.RHFhpAmqlOntwPilgxChauxjAdfj(WebRequest , CancellationToken )
>    en xxYoKTgHZoikGDMaKgOGehbpCAnpA.RHFhpAmqlOntwPilgxChauxjAdfj(zIoJbUcUEBbblFwoZJzUEObOoOvF , CancellationToken )
>    en rsyoJPQXiPBckwmpxiaucBIICdkO.RHFhpAmqlOntwPilgxChauxjAdfj(zIoJbUcUEBbblFwoZJzUEObOoOvF , CancellationToken )
>    --- Fin del seguimiento de la pila de la excepción interna ---
>    en rsyoJPQXiPBckwmpxiaucBIICdkO.RHFhpAmqlOntwPilgxChauxjAdfj(zIoJbUcUEBbblFwoZJzUEObOoOvF , CancellationToken )
>    en xxYoKTgHZoikGDMaKgOGehbpCAnpA.RHFhpAmqlOntwPilgxChauxjAdfj(WebRequest , CancellationToken )
>    en LeviEkEknBnAjEleOrDwkhyWgKPt.RHFhpAmqlOntwPilgxChauxjAdfj(WebRequest , CancellationToken )
>    en KbsAgUuvORdKoqrCVctFQLBBVLDd.JhJIOcekAxMkISEhsyEAGWCrQUYo(zIoJbUcUEBbblFwoZJzUEObOoOvF , Exception , CancellationToken )
>    en rsyoJPQXiPBckwmpxiaucBIICdkO.ncbYKqesqnWGQoHnZSgbXqqbEhvd.CKmCIghBLCzgeMkhFQbIfSZpCfoY(zIoJbUcUEBbblFwoZJzUEObOoOvF )
>    en zPsEjbKYyPRCPCLITmWwvwJGFoSo.YyWGKXxHvsJQJnGZUSfzTOovPuyj()
>    en NffZeQBAlZOdFYmEApVjBBDuPypC.RHFhpAmqlOntwPilgxChauxjAdfj(WebRequest , CancellationToken )
>    en LeviEkEknBnAjEleOrDwkhyWgKPt.RHFhpAmqlOntwPilgxChauxjAdfj(WebRequest , CancellationToken )
>    en xxYoKTgHZoikGDMaKgOGehbpCAnpA.RHFhpAmqlOntwPilgxChauxjAdfj(zIoJbUcUEBbblFwoZJzUEObOoOvF , CancellationToken )
>    en KXiXOoPzGHFtzqiOAzAJHRlMraQD.RHFhpAmqlOntwPilgxChauxjAdfj(zIoJbUcUEBbblFwoZJzUEObOoOvF , CancellationToken )
>    en xxYoKTgHZoikGDMaKgOGehbpCAnpA.RHFhpAmqlOntwPilgxChauxjAdfj(WebRequest , CancellationToken )
>    en LeviEkEknBnAjEleOrDwkhyWgKPt.RHFhpAmqlOntwPilgxChauxjAdfj(WebRequest , CancellationToken )
>    en xxYoKTgHZoikGDMaKgOGehbpCAnpA.RHFhpAmqlOntwPilgxChauxjAdfj(zIoJbUcUEBbblFwoZJzUEObOoOvF , CancellationToken )
>    en OScanJDTYEfAfkBsmwSPplwaIPYsA.RHFhpAmqlOntwPilgxChauxjAdfj(zIoJbUcUEBbblFwoZJzUEObOoOvF , CancellationToken )
>    en xxYoKTgHZoikGDMaKgOGehbpCAnpA.RHFhpAmqlOntwPilgxChauxjAdfj(WebRequest , CancellationToken )
>    en LeviEkEknBnAjEleOrDwkhyWgKPt.RHFhpAmqlOntwPilgxChauxjAdfj(WebRequest , CancellationToken )
>    en WTwmIjYXKQNqMnbnDXwOMHJtjsWA.RHFhpAmqlOntwPilgxChauxjAdfj(WebRequest , CancellationToken )
>    en LeviEkEknBnAjEleOrDwkhyWgKPt.RHFhpAmqlOntwPilgxChauxjAdfj(WebRequest , CancellationToken )
>    en xxYoKTgHZoikGDMaKgOGehbpCAnpA.RHFhpAmqlOntwPilgxChauxjAdfj(zIoJbUcUEBbblFwoZJzUEObOoOvF , CancellationToken )
>    en SFlARzXldpPoUmSmLChKYaNwCNBkA.RHFhpAmqlOntwPilgxChauxjAdfj(zIoJbUcUEBbblFwoZJzUEObOoOvF , CancellationToken )
>    en xxYoKTgHZoikGDMaKgOGehbpCAnpA.RHFhpAmqlOntwPilgxChauxjAdfj(WebRequest , CancellationToken )
>    en LeviEkEknBnAjEleOrDwkhyWgKPt.RHFhpAmqlOntwPilgxChauxjAdfj(WebRequest , CancellationToken )
>    en xxYoKTgHZoikGDMaKgOGehbpCAnpA.RHFhpAmqlOntwPilgxChauxjAdfj(zIoJbUcUEBbblFwoZJzUEObOoOvF , CancellationToken )
>    en vfKzFMSBFJCSXdqzFcQbNGcbqtqeb.RHFhpAmqlOntwPilgxChauxjAdfj(zIoJbUcUEBbblFwoZJzUEObOoOvF , CancellationToken )
>    en xxYoKTgHZoikGDMaKgOGehbpCAnpA.RHFhpAmqlOntwPilgxChauxjAdfj(WebRequest , CancellationToken )
>    en LeviEkEknBnAjEleOrDwkhyWgKPt.RHFhpAmqlOntwPilgxChauxjAdfj(WebRequest , CancellationToken )
>    en xxYoKTgHZoikGDMaKgOGehbpCAnpA.RHFhpAmqlOntwPilgxChauxjAdfj(zIoJbUcUEBbblFwoZJzUEObOoOvF , CancellationToken )
>    en rsyoJPQXiPBckwmpxiaucBIICdkO.RHFhpAmqlOntwPilgxChauxjAdfj(zIoJbUcUEBbblFwoZJzUEObOoOvF , CancellationToken )
>    --- Fin del seguimiento de la pila de la excepción interna ---
>    en rsyoJPQXiPBckwmpxiaucBIICdkO.RHFhpAmqlOntwPilgxChauxjAdfj(zIoJbUcUEBbblFwoZJzUEObOoOvF , CancellationToken )
>    en xxYoKTgHZoikGDMaKgOGehbpCAnpA.RHFhpAmqlOntwPilgxChauxjAdfj(WebRequest , CancellationToken )
>    en LeviEkEknBnAjEleOrDwkhyWgKPt.RHFhpAmqlOntwPilgxChauxjAdfj(WebRequest , CancellationToken )
>    en xxYoKTgHZoikGDMaKgOGehbpCAnpA.RHFhpAmqlOntwPilgxChauxjAdfj(zIoJbUcUEBbblFwoZJzUEObOoOvF , CancellationToken )
>    en QiBpTiGErJPLROBfLSGksuQbmFoy.RHFhpAmqlOntwPilgxChauxjAdfj(zIoJbUcUEBbblFwoZJzUEObOoOvF , CancellationToken )
>    en xxYoKTgHZoikGDMaKgOGehbpCAnpA.RHFhpAmqlOntwPilgxChauxjAdfj(WebRequest , CancellationToken )
>    en LeviEkEknBnAjEleOrDwkhyWgKPt.RHFhpAmqlOntwPilgxChauxjAdfj(WebRequest , CancellationToken )
>    en sEsBEJCVNcpeJlIlYdSOAPyzIUSm.QljkLjiNEwytHXdJYvRuIRbqgSDR(String , CookieContainer , String[] , String , gjjWBonpfbafpceFHeAQiYjeQpgIA , String[] )
> 00:36:27 flaresolver [x] Error: Error solving the challenge. Timeout after 100.0 seconds.
> 00:36:27 flaresolver [i] Response in 100.118 s
> 00:36:27 flaresolver [i] 127.0.0.1 POST http://localhost:8191/v1 500 Internal Server Error

**Comment by HDoujinDownloader** [comment]
Thanks for checking that.

I'm not sure why FlareSolverr is timing out-- I think this is more of a FlareSolverr issue than an HDoujin Downloader issue. If you want to attempt to debug it, you can enable debug-level logging for FlareSolverr by starting it manually (just run the `flaresolverr.exe` executable) with the `LOG_LEVEL` environmental variable set to `debug`. There's more information about this in the [FlareSolverr repository](https://github.com/FlareSolverr/FlareSolverr).

Alternatively, you can still get around Cloudflare without FlareSolverr. You can solve the Cloudflare challenge in your web browser, and then copy the cookies over to HDoujin Downloader. You need to copy the user agent string and `cf_clearance` cookie. This is explained in more detail with screenshots [here](https://github.com/HDoujinDownloader/HDoujinDownloader/wiki/Cloudflare#bypassing-cloudflare-manually).

**Comment by malokoko** [comment]
> Thanks for checking that.
> 
> I'm not sure why FlareSolverr is timing out-- I think this is more of a FlareSolverr issue than an HDoujin Downloader issue. If you want to attempt to debug it, you can enable debug-level logging for FlareSolverr by starting it manually (just run the `flaresolverr.exe` executable) with the `LOG_LEVEL` environmental variable set to `debug`. There's more information about this in the [FlareSolverr repository](https://github.com/FlareSolverr/FlareSolverr).
> 
> Alternatively, you can still get around Cloudflare without FlareSolverr. You can solve the Cloudflare challenge in your web browser, and then copy the cookies over to HDoujin Downloader. You need to copy the user agent string and `cf_clearance` cookie. This is explained in more detail with screenshots [here](https://github.com/HDoujinDownloader/HDoujinDownloader/wiki/Cloudflare#bypassing-cloudflare-manually).

The problem is with FlareSolverr. I set it to debug mode and it doesn't find the checkbox to verify that I'm human, so for now I will use manual mode.

I've also tried the latest version of FlareSolverr, 3.3.4, and I'm still getting the same error :/

**Comment by HDoujinDownloader** [comment]
Thanks for the update. It might be worth opening an [issue](https://github.com/FlareSolverr/FlareSolverr/issues/new/choose) with FlareSolverr if you already went through the trouble of getting the debug information. It looks like the 3.3.4 update was just to update the checkbox selector, so it's possible this is a case they overlooked.

Sorry I have nothing more helpful to offer than that right now. 😕

**Comment by HDoujinDownloader** [comment]
FlareSolverr has now had two new releases related to this issue-- I recommend giving the [latest version](https://github.com/FlareSolverr/FlareSolverr/releases/download/v3.3.6/flaresolverr_windows_x64.zip) a shot and seeing how it goes.

**Comment by capSAR273** [comment]
Still getting flaresolverr timeouts on the latest with nhentai

**Comment by HDoujinDownloader** [comment]
I'm closing this issue since it applies to older versions of FlareSolverr.

Discussion of FlareSolverr-related issues with nhentai will continue here: #314
