### ISSUE TITLE
yugenmangas.net: Page list from chapter is incomplete

### ISSUE THREAD

**Issue by exborn** [HDoujinDownloader/HDoujinDownloader#244]
It does not download the first two pages of all the chapters. Any downloaded chapter does not have a cover and neither does the next page. The following sheets of the chapter if they are downloaded well.

**Comment by HDoujinDownloader** [comment]
Fixed! Thanks for letting me know.

It should be working fine the next time you restart HDoujin Downloader!

**Comment by exborn** [comment]
Thank you very much, now it works really well.
