### ISSUE TITLE
Edited Module is removed and replaced with repo

### ISSUE THREAD

**Issue by ahmadi3d** [HDoujinDownloader/HDoujinDownloader#248]
I tried editing one of the modules to add support for a new website but the moment I edit the module and restart the application, the module is removed and its downloaded again! Is this functionality intended ? how can I disable it? Thank you.

**Comment by HDoujinDownloader** [comment]
It is intended behavior-- Modules are synced automatically every time you restart HDoujin Downloader, so any changes you make to them can end up getting overwritten. 

You can disable this behavior if you go to _**Tools > Module Browser**_ from the menu at the top of the program window, select the "Official Lua Repository", go to the "Options" tab, and uncheck the "Synchronize automatically" setting.

Alternatively, you can add your own repository by clicking the plus button above the repository list. You can specify a folder containing your own custom modules. The order the repositories appear in the list defines their priority, so if you want to override an existing module, just make sure your repository is on top.

The latter approach is preferable so you can still get automatic module updates.
