### ISSUE TITLE
ksk.moe Page Collection Error when Specific tags are used

### ISSUE THREAD

**Issue by mrreal100** [HDoujinDownloader/HDoujinDownloader#250]
If you try to go by tag, artist, etc. it won't download and gives a Page Collection Error:

Example
https://ksk.moe/tags/Paperback

Entering it would inform it sees it, but when pressing download it errors out.

**Comment by mrreal100** [comment]
Or  any combination of tags and it error's out.

**Comment by HDoujinDownloader** [comment]
These kinds of URLs weren't supported, by they are now (bcefa2f)!

When you add one of these URLs to the download queue, it will add all galleries on the current page. If you want to add multiple pages, use the **_Manga > Add from List_** feature from the menu at the top of the program window. You can then generate a range of URLs using

```
https://ksk.moe/tags/Paperback/page/(1-6)
```
