### ISSUE TITLE
porting with mono

### ISSUE THREAD

**Issue by pirate486743186** [HDoujinDownloader/HDoujinDownloader#26]
With mono, you could make your program crossplatform, even on android.

It will need some porting though.

**Comment by pirate486743186** [comment]
You could start with porting. Because of the porting, you'll have to rewrite some parts, but you are doing that already for opensourcing. So in theory, if you start with porting, you'll put in less effort, then if you do it the other way around.

**Comment by HDoujinDownloader** [comment]
I'm targeting NET Standard 2.0 as I move the codebase into separate libraries, which I believe is fully compatible with Mono, so no worries there.
