### ISSUE TITLE
Lezhin WEBP option not working

### ISSUE THREAD

**Issue by Fallen98** [HDoujinDownloader/HDoujinDownloader#268]
When trying to download from Lezhin with the WEBP option enabled it still downloads in the JPG format

**Comment by rs3mk** [comment]
Settings-> Save to-> Convert-> Edit image conversion rules-> Convert 

Remove convert webp to jpg

**Comment by Fallen98** [comment]
> Settings-> Save to-> Convert-> Edit image conversion rules-> Convert
> 
> Remove convert webp to jpg

Already did that, it's still downloading as JPG for me

**Comment by HDoujinDownloader** [comment]
I'm not sure Lezhin even serves WebP images anymore. 

Even though the images have a `.webp` file extension, they're actually just JPEG images. This is why HDoujin Downloader rewrites the file extension after downloading them. You can try saving the images in your web browser, and I think you'll encounter the same result.

**Comment by Fallen98** [comment]
> I'm not sure Lezhin even serves WebP images anymore.
> 
> Even though the images have a `.webp` file extension, they're actually just JPEG images. This is why HDoujin Downloader rewrites the file extension after downloading them. You can try saving the images in your web browser, and I think you'll encounter the same result.

No worries, I will convert them then to webp
