### ISSUE TITLE
800 websites?

### ISSUE THREAD

**Issue by pirate486743186** [HDoujinDownloader/HDoujinDownloader#27]
i'm counting 125 modules....

**Comment by HDoujinDownloader** [comment]
Some modules are generic in that they handle multiple domains (e.g. the modules dedicated to specific WordPress templates).

Aside from that, not every module is implemented in Lua. Lua modules are a relatively recent feature (and used for all future module development), with the majority implemented in C# and compiled into the executable itself. You can check them out by going to "Tools > Module Browser" in the program and selecting the "Internal" repository. Internal modules that handle multiple domains are consolidated into one item in the list, though (under the module named "*").
