### ISSUE TITLE
Add support for The Cloud Recess

### ISSUE THREAD

**Issue by ShadowHunter232** [HDoujinDownloader/HDoujinDownloader#280]
Could support be added for https://cloudrecess.io/

**Comment by Arekkusu1998** [comment]
Excuse me, @ShadowHunter232, but I can no longer access [Cloudrecess](cloudrecess.io) and I don't know how to contact the Admin. The Cloudflare barrage loops **endlessly**. Doesn't happen to you too? 
My access was neither banned nor restricted, so I don't know if it's just me or it's the website that's having problems.

**Comment by HDoujinDownloader** [comment]
The same thing happens on my end too.

I'll close this issue for now since the site appears to be dead, but feel free to reopen it if it becomes available again.
