### ISSUE TITLE
Waiting for Cloudflare...

### ISSUE THREAD

**Issue by Infel1** [HDoujinDownloader/HDoujinDownloader#285]
When I go to download from pages protected by Cloudflare. Those pages that when you enter them say something like "checking if the connection is secure." The moment I enter Hdoujin Downloader and place the link for the Manhwa, Manga or Manhua, a Cloudflare icon appears below that says "Waiting for Cloudflare" The thing is that because of that bug I can't download content from pages like Nartag.com and many others.

![WaitingforCloudflare](https://github.com/HDoujinDownloader/HDoujinDownloader/assets/36248950/a2e39d5c-c206-45de-97ed-07b7797abaca)

**Comment by HDoujinDownloader** [comment]
Have you tried updating the FlareSolverr plugin? Follow the instructions [here](https://github.com/HDoujinDownloader/HDoujinDownloader/wiki/FlareSolverr-IUAM-Challenge-Solver#updating-the-flaresolverr-plugin) to get the latest version.

Let me know if it works for you!

**Comment by Infel1** [comment]
> Have you tried updating the FlareSolverr plugin? Follow the instructions [here](https://github.com/HDoujinDownloader/HDoujinDownloader/wiki/FlareSolverr-IUAM-Challenge-Solver#updating-the-flaresolverr-plugin) to get the latest version.
> 
> Let me know if it works for you!

YES IT WORKED THANKS
