### ISSUE TITLE
[Suggestion] Change %GROUP% default value when no group found

### ISSUE THREAD

**Issue by X-Xadro** [HDoujinDownloader/HDoujinDownloader#288]
I have Chapters Naming configured with the value of %GROUP% at the end which works excellent on MangaDex in identifying which chapter belongs to which group.

But pretty much on every other website i download from it just shows "Unknown Group", it would be great if instead it just showing "Unknown Group" it shows the website name, like Asuratoon, FlameComics, Manga4Life etc.  even if its just the domain (without the .com .net etc.)

I guess the same goes for %SCANLATOR%, %TRANSLATOR% and %UPLOADER%  when their values are Unknown.

I am using this for Chapters Naming: `#%CHAPTER#100% - %TITLE% (%GROUP%)`

When downloading from Mangadex it shows this: `#001 - Ch. 1 (Flame Scans)`

But when downloading from Manga4Life it shows this: `#001 - Chapter 0 (Unknown Group)`

**Comment by HDoujinDownloader** [comment]
I just uploaded a new update that allows the `%WEB%` token in your chapter formatting string. This token gets replaced with the name of the website you're downloading from. You can now set your formatting string to something like: `#%CHAPTER#100% - %TITLE% (%GROUP||WEB%)`

If the `%GROUP%` value is unknown, it will use the `%WEB%` value instead. You can chain together any number of tokens like this-- See here for details: https://github.com/HDoujinDownloader/HDoujinDownloader/wiki/Formatting-Strings

**Comment by X-Xadro** [comment]
Thank you! I'm very happy with this!
