### ISSUE TITLE
E-hentai/Ex-hentai Login Issue

### ISSUE THREAD

**Issue by hibikikuze4dan** [HDoujinDownloader/HDoujinDownloader#299]
It looks like e-hentai has implemented a captcha solver on their login and it is preventing that application from logging in and getting archive information from links provided by the user.

**Comment by HDoujinDownloader** [comment]
Indeed, I'll have to come up with some way of dealing with the captcha. I have some ideas, but in the meantime, you can copy your cookies into HDoujin Downloader manually by following the instructions here: https://github.com/HDoujinDownloader/HDoujinDownloader/wiki/Logging-In-To-ExHentai#adding-login-cookies-manually

Please follow #298 for updates on this issue.
