### ISSUE TITLE
Site access occassionally blocked by Cloudflare

### ISSUE THREAD

**Issue by StormJumper** [HDoujinDownloader/HDoujinDownloader#30]
I am having multiple sites that worked previous now having cloudflare blocking? To not being able to add the manga to the bookmark.

WebLovemanga, Isekaiscan. So what is happening to cloudflare to cause this problem? I am also using the alternative cloudflare check as well. Also sites where I saved my login/pswd don't work with HDD anymore as well Kissaway is one of them.

**Comment by HDoujinDownloader** [comment]
> I am having multiple sites that worked previous now having cloudflare blocking

Make sure that you're using the [FlareSolverr plugin](https://github.com/HDoujinDownloader/HDoujinDownloader/wiki/FlareSolverr-IUAM-Challenge-Solver) with the [latest release](https://github.com/HDoujinDownloader/HDoujinDownloader/releases/latest) of HDoujin Downloader, which should work fine for the majority of Cloudflare-enabled websites. I did notice that it's occasionally struggling with newer challenges that are being given to specific IP addresses, which is currently being discussed here: FlareSolverr/FlareSolverr#184

> WebLovemanga

WeLoveManga doesn't use Cloudflare, but its own "in house" solution. If you update to the [latest release](https://github.com/HDoujinDownloader/HDoujinDownloader/releases/latest), it should be working normally. Make sure that your [module repositories](https://doujindownloader.com/module-repositories/) are set up properly so it can download the updated modules.

> Isekaiscan

This site doesn't use Cloudflare either, and should be working now too. That said, there are multiple different domains that go by this name, so let me know what site you want me to look at specifically if it's still not working.

> my login/pswd don't work with HDD anymore

Let me know what sites you're having login problems with, and I'll check it out. Kissaway (now KLManga) seems to now be using a captcha on their login page, so I'll update the login procedure accordingly (#31).

**Comment by StormJumper** [comment]
mangapark.net is now having cloudflare issues.

**Comment by StormJumper** [comment]
Isekaiscan is still using cloudflare blocking filter....

**Comment by HDoujinDownloader** [comment]
All of the sites mentioned now have either disabled Cloudflare or are currently working the FlareSolverr plugin, so I'm closing this issue.
