### ISSUE TITLE
Add support for lezhin.jp

### ISSUE THREAD

**Issue by Arekkusu1998** [HDoujinDownloader/HDoujinDownloader#302]
Good morning @HDoujinDownloader!
First of all, I want to warmly thank you for all the work you do on this software, it is really much appreciated🤗. I'm a new user.
I kindly wanted to ask if it is possible to add support for the Japanese version of Lezhin as well.

**Comment by Arekkusu1998** [comment]
Good morning, @HDoujinDownloader. I hope you're fine. Thanks again for your wonderful software🤗! 
Since I found a way to download from Lezhin Japan, I'm closing the issue, so there's one less to think about.

**Comment by HDoujinDownloader** [comment]
Thank you so much for your patience and kind words. ❤️ 

I've now added support for lezhin.jp-- I apologize for the wait!

If any further issues pop up, let's continue discussing them in #382.
