### ISSUE TITLE
[REPORT] lekmanga | like-manga

### ISSUE THREAD

**Issue by FevLoad** [HDoujinDownloader/HDoujinDownloader#311]
Hello there, I couldn't add any manga nor chapters or team to be downloaded
always showing in the logs view
skipped or un-updated module
tell me what info you need to make this issue fixed
example:
- https://lekmanga.net/manga/re-monster/
- https://like-manga.net/manga/the-horizon/

**Comment by HDoujinDownloader** [comment]
Both sites have now been added, and should be working the next time you restart HDoujin Downloader!
