### ISSUE TITLE
[Feature Request] Implement Volume and Chapter-Based Directory Structure from MangaDex Information

### ISSUE THREAD

**Issue by RedRain77** [HDoujinDownloader/HDoujinDownloader#312]
Hey Squidy,

I've been using MangaDex recently and noticed that they provide some volume information within the chapter titles. 
Would it be possible to incorporate this into the directory structure syntax?
Specifically, I'm interested in a directory format that looks like this:
Attack on Titan/Volume #01/Chapter #01 - Title\p001

Thanks so much for all your hard work on this program!

**Comment by HDoujinDownloader** [comment]
I'm replying to this a little late, but this is already possible! 

For chapters, go to **_Settings > Save to > Chapters_**, and set your chapter formatting string to `Volume %volume#%\Chapter %chapter#% - %subtitle%`. 

For pages, go to **_Settings > Save to > General_** and set your page formatting string to `p%page%`.

This should achieve what you want, but let me know if you have any trouble!
