### ISSUE TITLE
Please add these new websites

### ISSUE THREAD

**Issue by Infel1** [HDoujinDownloader/HDoujinDownloader#318]
Currently I read a lot of manhua and manhwa. I would like you to add these websites to the program. Thanks for your work :3

- https://shadowmangas.com/
- https://taurusmanga.com/
- https://visorikigai.net/

**Comment by HDoujinDownloader** [comment]
All of these websites have now been added, and should be working the next time you restart HDouijn Downloader!

Let me know if you run into any problems.
