### ISSUE TITLE
[Request] - manjanoon & [Report] - lekmangs 

### ISSUE THREAD

**Issue by FevLoad** [HDoujinDownloader/HDoujinDownloader#321]
Hello there squidy

➖ I want to request adding Manjanoon.org
With the ability to download the whole chapters just by adding the manga page URL
Example: https://manjanoon.org/manga/nn-mr-villain-husband-the-one-you-should-be-obsessing-with-is-over-there/

And I saw that lekmang site's module need to be fix it doesn't catch any chapters at all and in case it it's working it only catch the last chapter like this URL
Example: https://lekmanga.net/manga/after-school-lessons-for-unripe-apples/

**Comment by HDoujinDownloader** [comment]
Both of these sites should now be working as expected! Let me know if you have any other problems.
