### ISSUE TITLE
Theme is not persistent during restart

### ISSUE THREAD

**Issue by MimoKar** [HDoujinDownloader/HDoujinDownloader#326]
When I change the theme from default to another than it is not saved and after restart it is back to default.
Or would it be possible to follow system theme type (dark/light)?

**Comment by HDoujinDownloader** [comment]
Theme support is still experimental right now, and there are a lot of visual bugs I wanted to iron out before having it be an official feature. The reason I originally decided not to have the setting persist is that a bad stylesheet can end up making the UI completely unusable. I'm rewriting the theming system right now to be more efficient and less janky, but I need a bit more time before it's ready for release. It will respect system theme settings when it's done.

Although, I understand it's a huge hassle to have to apply it every time you start the program. I'll definitely make this setting persistent in a future update.

**Comment by ale5000-git** [comment]
@HDoujinDownloader
If possible it would be nice to also have an option (even if advanced it is fine) to disable column ordering (so cloumn labels aren't clickable) but still allow manual ordering.
I usually order download list manually and it is a bit annoying when I wrongly hit the column label and change all the ordering.

**Comment by HDoujinDownloader** [comment]
I've added a `Interface.Main.ApplyThemeOnStartup` setting under **_Tools > General settings > Advanced settings_**. This will be present in the next program update, so enable it to have your selected theme persist across restarts.

@ale5000-git I've also added a `Interface.DownloadQueue.ColumnHeaderSortingEnabled` setting for the next program update, which you can toggle off to disable column ordering.

**Comment by ale5000-git** [comment]
Thank you very much :-)

**Comment by HDoujinDownloader** [comment]
Both of these settings are now available as of as version 2024.8.21.0!
