### ISSUE TITLE
I'm only interested in the English version of a manga. How do I prevent the app from redownloading in other languages? (from mangadex)

### ISSUE THREAD

**Issue by 0fie** [HDoujinDownloader/HDoujinDownloader#330]
![image](https://github.com/HDoujinDownloader/HDoujinDownloader/assets/151028199/80dabbdd-8dbb-4fd6-9d97-0cda54c94cd4)

**Comment by HDoujinDownloader** [comment]
Haha, I assume you figured it out. 

For anyone else wondering, you need to go to _**Tools > Site settings**_, select "MangaDex", and then check off your preferred languages. Otherwise all languages are downloaded by default.
