### ISSUE TITLE
(site request) bilibilicomics.net

### ISSUE THREAD

**Issue by xeolod** [HDoujinDownloader/HDoujinDownloader#342]
Site - https://bilibilicomics.net/

Fan backup of now dead bilibilicomics. All comics are free.

1. Please allow downloading of original image type and original size of the image.
2. Image types (png, webp, jpg, jpeg) of some chapters of a same comic are different and the quality is also different.

---

![image](https://github.com/HDoujinDownloader/HDoujinDownloader/assets/129925515/f6ac2949-f0bd-4ddc-9497-350629f3eaf0)

**Comment by ale5000-git** [comment]
@HDoujinDownloader
The API seems different so BilibiliComics.lua is now useless.

**Comment by HDoujinDownloader** [comment]
Added! Let me know if you have any problems.

Sorry for the wait!
