### ISSUE TITLE
Anchira.to returns "The downloaded file was 0 bytes" on all pages

### ISSUE THREAD

**Issue by megu230** [HDoujinDownloader/HDoujinDownloader#345]
When trying to download anything from anchira, all downloaded pages give out the error mentioned in the title. When opening the website on my browser, no captcha shows up to be solved. I don't use a VPN.

Log is attached below.
[1716553404.log](https://github.com/HDoujinDownloader/HDoujinDownloader/files/15434225/1716553404.log)

**Comment by HDoujinDownloader** [comment]
This has to do with a recent update they made that added a redirect when accessing the images. HDoujin Downloader isn't handling the redirect properly, resulting in the issue you're describing.

I need to release a program update to fix it properly, but there is a workaround available right now: Go to **_Tools > General settings_**, and under "Advanced settings", disable the `Network.Http.OverrideAutomaticRedirection` setting. After that, downloads should resume as expected.

I don't recommend leaving this setting disabled, though, so please re-enable it after the next program update.

**Comment by HDoujinDownloader** [comment]
Anchira no longer exists, so I'm going to close this issue.
