### ISSUE TITLE
Again the error of the chapters in N/A with a website that you have added

### ISSUE THREAD

**Issue by Infel1** [HDoujinDownloader/HDoujinDownloader#349]
When I went to download a manhwa at "https://taurusmanga.com/" in the chapters section the N/A message appeared and you had already solved that "error" something that I almost forgot is that as you can see the name does not appear either of the manhwa but the message of "605 available chapters"
![Screenshot 2024-05-27 10-26-35](https://github.com/HDoujinDownloader/HDoujinDownloader/assets/36248950/34fd01be-02e5-4903-a146-e8a350d5db23)

**Comment by Infel1** [comment]
https://mangas.in/
https://www.leercapitulo.co/
https://mg.mundodrama.site/
https://mantraz-scan.com/
https://visortecno.com/
https://hadesnofansub.com/
https://emperorscan.org/
https://leerolymp.com/

I would also like you to add those websites that gave me the same "N/A" error or simply did not appear to download

**Comment by HDoujinDownloader** [comment]
TaurusManga should now be working as expected the next time you restart HDoujin Downloader! 

As for the other requests, I'll refer to #323.
