### ISSUE TITLE
Updater Error for Extra Modules

### ISSUE THREAD

**Issue by PDPComics** [HDoujinDownloader/HDoujinDownloader#358]
I have a latest version (2024.3.25) in my non-system folder. Activated to full version, And clicked “Help > Check for Updates > Download Now” Getting Below Note.

Updater:

The update did not complete successfully. HDoujin Downloader may not have write permissions for this directory, To solve this problem, run the program as Administrator or move it to a non-system directory.

Please guide us, How to fix this issue ?

**Comment by HDoujinDownloader** [comment]
No worries-- See #75 for an explanation of why this is happening, as well as a workaround so you can download them manually.

**Comment by ale5000-git** [comment]
@HDoujinDownloader
Isn't possible to detect when the download isn't working and display a more specific error message?

**Comment by HDoujinDownloader** [comment]
@ale5000-git Yes, definitely. I should probably do that next time I update the updater.

The underlying issue here has been resolved for a while on my end, but I've been putting off releasing a new version of the updater because it tends to trigger antivirus software, which is always a headache. But it has to be done eventually.

**Comment by ale5000-git** [comment]
@HDoujinDownloader
If you want you can scan the new file here: https://www.virustotal.com/
and then report the false positive to the antivirus that detect it in advance,

**Comment by HDoujinDownloader** [comment]
@ale5000-git That's generally what I do, but some of the heuristic-based scanners stay quiet until it does something "suspicious" (i.e. downloading update files 🙄).

**Comment by ale5000-git** [comment]
@HDoujinDownloader
I don't know the exact detection, but usually if you put the files in an encrypted zip archive then the AV shouldn't be able to detect  it.
Or to be more safe and encrypted rar archive.
RAR also have the option to encrypt file list, so without password the AV will not be able the filenames inside thr archive.

**Comment by HDoujinDownloader** [comment]
@ale5000-git It's an interesting suggestion. I'm not sure if it's the fact the update archive contains executables or something else that triggers the false-positives (these heuristics-based systems are kind of black boxes, for good reason), but it's possible you're into something.

**Comment by ale5000-git** [comment]
Usually the AV extract the archives (I'm not sure if in RAM or in a temp folder) and detect the content, they won't be able to do something on encrypted content.
