### ISSUE TITLE
Domain Management isnt work.

### ISSUE THREAD

**Issue by Infel1** [HDoujinDownloader/HDoujinDownloader#375]
Well... I want to summarize this. I follow several websites and they tend to constantly change domains so HDoujin does not detect them again when you put a URL of some Manga, Manhwa or Manhua and you have to add the site to the Hdoujin database again. When I try to use "Domain Management" to have Hdoujin detect the new domain, it just doesn't work even though everything on the website is the same.

Below I will leave several examples of what I mean: 

1. https://lectorespanol.com NEW DOMAIN: https://panconcola.com/
2. https://es.ikigaiweb.lat NEW DOMAIN: https://visualikigai.com/
3. https://lectormh.com NEW DOMAIN: https://mh.twobluescans.com/

Hopefully, in a future Hdoujin update, we won't have to worry about those annoying changes to website domains.

**Comment by HDoujinDownloader** [comment]
It should work, you might just have the domains backwards. The first field is the domain you want to map, and the second one is the domain you want to map it to. Something like this will work:

![image](https://github.com/user-attachments/assets/b617fb61-a405-461a-80a3-826eb9dedf82)

I realize how the ordering could be confusing-- I'll see if I can update the interface to improve clarity.

In any case, I explicitly added support for all of the websites mentioned, so they should all be working now.

The next program update will have better generic module support, so this will be less and less of a problem as I develop those further. 👍 For now, please keep reporting them and I'll do my best to fix them ASAP.
