### ISSUE TITLE
Fix download viewcartoon.com

### ISSUE THREAD

**Issue by noneplayers** [HDoujinDownloader/HDoujinDownloader#378]
The image arrangement is incorrect. The image is not fully downloaded. Please check if possible.

**Comment by HDoujinDownloader** [comment]
Sorry for the wait! It should be working now.

This site is really unusual in that the images are stored across multiple PDFs that are decoded in the browser. I needed to release a new program update to accommodate the multiple PDFs. Just make sure you update first by going to **_Help > Check for updates_**.
