### ISSUE TITLE
AsuraScans Domain Change + Chapter URL Pattern Change

### ISSUE THREAD

**Issue by ahmadi3d** [HDoujinDownloader/HDoujinDownloader#379]
Hello, AsuraScans domain has changed to https://asuracomic.net/ and its URL pattern has changed as well, instead of 
https://asuracomic.net/series/1231252-murim-login
its now something like this:
https://asuracomic.net/series/murim-login-ed19e4a5
Meaning it now has a hash in the end instead of a number in the beginning.

Thank you!

**Comment by HDoujinDownloader** [comment]
This website should be working as expected now thanks to 56f107a and 1dc65c4!
