### ISSUE TITLE
Fix downloads for webtoons.com

### ISSUE THREAD

**Issue by mainqpalzm** [HDoujinDownloader/HDoujinDownloader#38]
Downloading/grabbing chapters from www.webtoons.com (LineWebtoon) is not working in [Version 2021.10.12] but,
works in [Version 2021.2.11] I add webtoon to download list, start downloading it, HDoujin Downloader starts grabbing chapters and after 10 minutes it still is grabbing chapters

**Comment by HDoujinDownloader** [comment]
I can't seem to reproduce the problem you're describing with the current release ([v2021.10.12.0](https://github.com/HDoujinDownloader/HDoujinDownloader/releases/tag/v2021.10.12.0)). The URLs I tested from webtoons.com did not seem to present any problems and the chapters list was fetched as expected.

Could you send me an example URL to look at that demonstrates this problem?

**Comment by mainqpalzm** [comment]
I tested fresh install on other machines, same error, which link did four you work.

**Comment by mainqpalzm** [comment]
?

**Comment by mainqpalzm** [comment]
I found out that this bug (Chapters was fetched but when I start download, status from grabbing chapters wont change.) in (Version 2021.11.8) is in my location, because when I turn on VPN I can download from www.webtoons.com (LineWebtoon).
Sorry for troubles.

**Comment by mainqpalzm** [comment]
Fix did not work for me in [Version 2021.11.15]

Pictures and Log File in zip file.

**Comment by mainqpalzm** [comment]
Fixed order

**Comment by mainqpalzm** [comment]
[Pictures and Log File.zip](https://github.com/HDoujinDownloader/HDoujinDownloader/files/7551570/Pictures.and.Log.File.zip)

**Comment by HDoujinDownloader** [comment]
Thanks a lot for all of the information you've provided so far. The "fix" in version 2021.11.15.0 was just to deal with the infinite loop it was running into when grabbing chapters.

@mainqpalzm: Enable logging by going to **_Help > Enable Diagnostics_**, disable the VPN or switch to a location that doesn't work, and then add a URL from Webtoons to the download queue. Then look inside of the "log" folder inside of your HDoujin Downloader folder, and you should see a file named something like "XXXXXXXXXX-webtoons.com.log". Send it to me, and I'll check it out. The log file will contain the HTML of the webpage, and from there I should be able to determine why it's unable to extract the chapters properly.

**Comment by mainqpalzm** [comment]
[log.zip](https://github.com/HDoujinDownloader/HDoujinDownloader/files/7593253/log.zip)

**Comment by HDoujinDownloader** [comment]
Thank you for sending the log files.

Did you see "N/A" for the chapter count for all of these URLs? Nothing stands out as unexpected, so I'm just confirming that these were generated with the VPN turned off.

**Comment by mainqpalzm** [comment]
Did you see "0/0" for the chapter count for all of these URLs? 
[Yes]

so I'm just confirming that these were generated with the VPN turned off.
[Yes]

**Update**: I just uploaded a module update for this site, so restart HDoujin Downloader and give it a shot. Let me know if it solves the problem for you.
[It solved problem, all works now, tested on multiple links]

Thanks

**Comment by HDoujinDownloader** [comment]
> It solved problem, all works now, tested on multiple links from webtoons.com

Glad to hear it! ❤️
