### ISSUE TITLE
Domain management does not detect websites

### ISSUE THREAD

**Issue by Infel1** [HDoujinDownloader/HDoujinDownloader#380]
![Screenshot 2024-07-29 23-25-30](https://github.com/user-attachments/assets/9591e84c-ca36-4337-9ce4-96a9e4a6b74d)
I did what you told me and put the websites in the correct order and it worked, but now there is a problem. The domain management is not working, I repeated the process several times and even restarted the program and there was no response, it simply did not detect the website

**Comment by HDoujinDownloader** [comment]
It turns out it doesn't redirect properly when there are subdomains, thanks for catching that. I've got it fixed on my end, so it'll be working as expected with the next program update.

I also update the relevant module, so the website in question should be working fine now either way!
