### ISSUE TITLE
[Bug] Bookmark shows multiple instance of the same website title

### ISSUE THREAD

**Issue by ahmadi3d** [HDoujinDownloader/HDoujinDownloader#381]
Hello, As you can see from the following image, the bookmark has a bug that shows multiple instances of the same title. For example, you can see "asurascans.net" is repeated several times. When I click each one of them, it shows the correct comics and the list items are the same, which means it's only a visual bug on the bookmark list itself, and the logic behind filtering is correct. I would appreciate it if you could fix this. Thank you!

![image](https://github.com/user-attachments/assets/126db0f4-9e45-4942-80fa-372c9d63c859)

**Comment by mrstan3772** [comment]
- Mysterious, I think it must be a bug if domains are identical.
- After a domain name update, it would be best to delete all bookmarks corresponding to an older address and replace them with the newer address. 
- Freak Comic or Manhwa Freak is permanently closed or has completely changed its name, assuming I'm not mistaken. 
- Regarding Asura Scans, it's no longer possible to update bookmarks. The urls for both series and chapters are contains a single alphanumeric string that regularly changes. A special system would have to be created to record chapter URLs according to predefined rules.

**Comment by HDoujinDownloader** [comment]
I've got a fix for this ready that will be present in the next program update. I wasn't able to reproduce it, but I did narrow down some potential causes/added duplicate checks to prevent the same website from appearing more than once. I'll upload the new version soon, so hold out until then! 🤞🤞

**Comment by HDoujinDownloader** [comment]
This should be resolved now with the latest program update!
