### ISSUE TITLE
[Lezhin (ALL LANGUAGES)] website update 

### ISSUE THREAD

**Issue by BereBereBeer** [HDoujinDownloader/HDoujinDownloader#382]
they recently changed their layout. the urls seems to be the same but I get the error message -Failed to fetch chapters-

**Comment by mrstan3772** [comment]
Encrypted... module... 😔😭

**Comment by Arekkusu1998** [comment]
@BereBereBeer , I would suggest You changing the title to 

> [Lezhin (**ALL LANGUAGES**)] website update

because the same bug occurs with Lezhin version in other languages: **English**, **Korean**, **Japanese** and **Spanish**. The problem is systemic. Our only hope is that Builder fixes the bug or creates a new software's version, maybe including the other two languages ​​(I opened an Issue myself about it: #302). 
Read [here](https://github.com/manga-download/hakuneko/issues/7305).

**Comment by HDoujinDownloader** [comment]
@mrstan3772 I know, it's not ideal, I'm sorry. 😭😭

I just uploaded a quick fix, so it should be working again (at least the English, Korean, and Japanese websites-- I think the Spanish one is a little different). Let me know how it goes for you, and if there's still any trouble I'll see what I can do.

**Comment by mrstan3772** [comment]
@HDoujinDownloader Awesome!!!

**Comment by Arekkusu1998** [comment]
Thanks so much for Your promptness, @HDoujinDownloader!!
However, while the version for the English website is operational again, I cannot view any content from the Korean and Japanese ones. When I paste the Manga URL, the usual writing `getting info from https://www.lezhin ...` appears below, but then anything apperas. Maybe I'm doing something wrong, but I double-checked my login details and they're fine.

**Comment by Arekkusu1998** [comment]
Thanks so much for Your promptness, @HDoujinDownloader!!
However, while the version for the English website is operational again, I cannot view any content from the Korean and Japanese ones. When I paste the Manga URL, the usual writing `getting info from https://www.lezhin ...` appears below, but then anything apperas. Maybe I'm doing something wrong, but I double-checked my login details and they're fine. The KR and JP webtoons are only displayed when I access the websites on the PC at the same time. (* confused *)

**Comment by Arekkusu1998** [comment]
Thanks so much for Your promptness, @HDoujinDownloader 😊!!
The version for the **English** website is operational again, however no content is displayed from the **Korean** and **Japanese** ones, unless I access the respective websites from my PC at the same time.

**Comment by Arekkusu1998** [comment]
Thanks so much for Your promptness, @HDoujinDownloader 😊!!

**Comment by HDoujinDownloader** [comment]
@Arekkusu1998 Are you still having problems? I noticed you updated your comment a couple of times.

**Comment by Arekkusu1998** [comment]
Sorry for the wait in replying: at first, I had a little catch about switching from a language to another, but then I realized what mistake I was making. Thank You very much.
