### ISSUE TITLE
New Hdoujin version slow with "Reading bookmarks" at startup

### ISSUE THREAD

**Issue by Raphael98** [HDoujinDownloader/HDoujinDownloader#384]
Hey,

I saw that there was an new update, so I decided to update, but now the application is slow to start up. It seems it happens at the "Reading bookmarks" part.

I’ve already tried a fresh install and re-importing my bookmarks, but that is slow as well.

This isn't an issue with the previous version.

**Comment by HDoujinDownloader** [comment]
Thanks for letting me know, I'll investigate and see what I can find. I did make some updates involving how bookmarks are loaded in response to #381, and it's possible a change I made there is a the culprit. I'll upload a fix ASAP once I figure it out.

Would you be willing to send me your bookmarks file (`bookmarks.dat`) to import on my end? You can send it to the support email address on the "About" tab, or upload it somewhere and send it through the [contact form](https://doujindownloader.com/contact/).

**Comment by HDoujinDownloader** [comment]
Thanks a lot, that makes things a lot easier. 👍 I was able to reproduce the problem on my end, so I'll figure out the cause and get back to you!

**Comment by HDoujinDownloader** [comment]
The issue should be resolved now with the latest update. Let me know if anything else comes up.

Thanks again for your help!
