### ISSUE TITLE
Lezhin (EN/KR/JA) doesn't work

### ISSUE THREAD

**Issue by Arekkusu1998** [HDoujinDownloader/HDoujinDownloader#392]
Have they changed something? I don't think so, but since yesterday I can no longer retrieve the chapters in any language version.

**Comment by HDoujinDownloader** [comment]
I think it's a bug in the login process. If you go to **_Tools > Web Browser_**, navigate to Lezhin, log in manually, and then try downloading, does it start working again?

**Comment by HDoujinDownloader** [comment]
Thanks a lot for confirming-- I might have to release a new program update to address this. I need to do a little bit more investigating, and I'll let you know what I figure out.

**Comment by mrstan3772** [comment]
I hope we'll be able to connect automatically again 😱

**Comment by Arekkusu1998** [comment]
Thanks for Your promptness, @HDoujinDownloader! It works.

**Comment by HDoujinDownloader** [comment]
Automated login should now be working again with the latest release. Let me know how it goes!

**Comment by Arekkusu1998** [comment]
Yeah, I confirm.
