### ISSUE TITLE
Asurascans website update broke page download

### ISSUE THREAD

**Issue by ahmadi3d** [HDoujinDownloader/HDoujinDownloader#402]
Hello
Asurascans just updated their website, after this update the chapters are still detected but when the downloader tries to download the pages it simply says "Completed" without downloading any page.
Sample:
https://asuracomic.net/series/wandering-warrior-of-wudang-d8c41b2f
Thank you!

**Comment by HDoujinDownloader** [comment]
It should be resolved now!
