### ISSUE TITLE
site request: Manhwa web

### ISSUE THREAD

**Issue by Infel1** [HDoujinDownloader/HDoujinDownloader#403]
https://manhwaweb.com/

**Comment by HDoujinDownloader** [comment]
Added! Let me know if you have any issues with it.

I did notice one quirk where sometimes the `content-length` header returned by the site would differ from the actual image size (basically, it's reporting incorrect image sizes). This doesn't affect the download and you should get all images anyway, but you might see a "Some failed" error.

If it gets annoying, you can disable this check by going under **_Tools > General settings > Advanced_**, and unchecking "Downloads.VerifyContentLength".
