### ISSUE TITLE
Preserve original Pixiv filenames

### ISSUE THREAD

**Issue by Arekkusu1998** [HDoujinDownloader/HDoujinDownloader#409]
Good Week, @HDoujinDownloader, I hope everything is fine.
Referring to an old Issue, #252, I wanted to know if there's a way to set the software to preserve **titles** (usually in Japanese, less often in English) of every Pixiv's image. F.e. I bulk downloaded [this artist](https://www.pixiv.net/en/users/37577/artworks), but the results are titled with numbers: 001, 002, 003, etc.
The only way I've to preserve every title is to insert the urls of each post, _one by one_ ... gosh, what a terrible slog😨!

**Comment by HDoujinDownloader** [comment]
This is something I've been meaning to do for a while. I've added a new page naming token, `%PTITLE%`, which corresponds to the title of a given image (or the original file name for images that don't have a title). This will be present in the next update-- Just add it to your page formatting string under **_Settings > Save to > General_**.

My heart goes out to you if you really were doing this manually. 😭😭

Sorry for late response to this one!

**Comment by HDoujinDownloader** [comment]
This should now be working with the current release! Let me know if you have any problems or questions.

**Comment by Arekkusu1998** [comment]
> My heart goes out to you if you really were doing this manually. 😭😭

Lol, this part really made me smile: thanks so much for solidarity!
Anyway, I think I'm doing something wrong. I formatted the string from `%PAGE%` to `%PTITLE% %PAGE%`, but images are just numbered, as usual. No Japanese titles have been added, which You can see [here](https://www.pixiv.net/en/users/37577/artworks?p=7) even without registering on Pixiv.
![Immagine](https://github.com/user-attachments/assets/cbebd60b-c869-4fa5-b838-cc9154874604)

**Comment by HDoujinDownloader** [comment]
You're not doing anything wrong! I added support for image titles without actually uploading a patch to the Pixiv module to take advantage of it-- Airheaded behavior on my part.

I'm working on a couple of other Pixiv-related changes to make the download process faster, so I'm going to push this out until the next program update. Please hold out until then!

**Comment by HDoujinDownloader** [comment]
All right, give this another shot with the latest program update! 🤞🤞

**Comment by Arekkusu1998** [comment]
> All right, give this another shot with the latest program update! 🤞🤞

Yes, I confirm that titles now appear on each file. Thank you so much for the update, @HDoujinDownloader!!
