### ISSUE TITLE
[Lezhin EN/KR/JA] Fetch page issue

### ISSUE THREAD

**Issue by mrstan3772** [HDoujinDownloader/HDoujinDownloader#410]
Update is necessary due it can no longer get pages.

**Error Log**

```
http        [x] Exception was thrown when accessing https://www.lezhinus.com/lz-api/v2/cloudfront/signed-url/generate?contentId={id}&episodeId={id}&purchased=true&q=0&firstCheckType=P
```

**Thanks**

**Comment by Arekkusu1998** [comment]
Not only Lezhinus, @mrstan3772, but also Lezhin Korea and Japan.

**Comment by HDoujinDownloader** [comment]
Confirmed-- Accessing this API endpoint now requires an `authentication` header with a bearer token. 

I'm currently investigating the issue, and I'll see what I can do to fix it.

**Comment by HDoujinDownloader** [comment]
@BereBereBeer Really appreciate the offer, thank you. If it ends up being necessary I may take you up on that.

I just uploaded a new fix, so let me know how it goes now. You don't need to manually copy in your token or anything, so don't worry about that.

**Comment by mrstan3772** [comment]
> @BereBereBeer Really appreciate the offer, thank you. If it ends up being necessary I may take you up on that.
> 
> I just uploaded a new fix, so let me know how it goes now. You don't need to manually copy in your token or anything, so don't worry about that.

It seems to be working again!

**Comment by Arekkusu1998** [comment]
I confirm: it works again for me too. Thank You very much!!
