### ISSUE TITLE
HDoujin does not detect the website: https://zonaemperor.com/

### ISSUE THREAD

**Issue by Infel1** [HDoujinDownloader/HDoujinDownloader#411]
This website was formerly: https://seriesemperor.com/ one of the websites that has a template in the program.

**Comment by HDoujinDownloader** [comment]
It looks like they commented out the part of the HTML used to detect the template. I'll update the template check accordingly.

**Comment by HDoujinDownloader** [comment]
It should start detecting it again the next time you restart HDoujin Downloader. 

Let me know if it stops working again!
