### ISSUE TITLE
E-Hentai/Ex-Hentai - Unable to get pages after new DOM updates to the websites.

### ISSUE THREAD

**Issue by hibikikuze4dan** [HDoujinDownloader/HDoujinDownloader#413]
The following was recently posted to the E-Hentai Minor Updates, Fixes, minor tweaks to existing functionality, minor new features board:

2024-10-25

- The previously announced backend and DOM changes are now live for a section of the site, let me know if you encounter any issues with this NOT related to outdated scripts.

The previously announced being:
- A test build that adds support for upcoming changes to image and thumbnail handling is now running on the onion site. The changes are mostly internal, but there are some thumbnail-related DOM changes in case people want to check for script compatibility. This will be pushed to the main site in a few days.

The changes made seem to be causing the downloader to be unable to get the pages for potential archives.

![Screenshot 2024-10-25 070045](https://github.com/user-attachments/assets/edc03ed1-0ac0-4bda-be10-79216ac44281)

Let me know if there's anything else I can provide to help with any debugging efforts.

**Comment by HDoujinDownloader** [comment]
Thanks a lot for this very detailed and helpful report.

I'll upload a fix by tomorrow!

**Comment by HDoujinDownloader** [comment]
This should be resolved now with the latest release. Let me know how it goes!

**Comment by hibikikuze4dan** [comment]
> This should be resolved now with the latest release. Let me know how it goes!

Yep, was able to download without issue 🎉 ! Thanks for the quick updated 👍 .
