### ISSUE TITLE
Add support for kemono.party

### ISSUE THREAD

**Issue by mrreal100** [HDoujinDownloader/HDoujinDownloader#42]
Wanted to ask if it hasn't been added but does it have https://kemono.party/ support. If not can it be added?

**Comment by HDoujinDownloader** [comment]
This site isn't supported yet, but it uses the DDoS-Guard service, which makes it a bit tricky to scrape. Cloudflare's equivalent service is handled via FlareSolverr, which has an open issue for DDoS-Guard support (FlareSolverr/FlareSolverr#49), but who knows when it will actually be implemented.

I might look into implementing a workaround of my own.

**Comment by HDoujinDownloader** [comment]
Support for this site was added in commit 42f20d6.
