### ISSUE TITLE
Unable to Download from niyaniya.moe

### ISSUE THREAD

**Issue by Baine** [HDoujinDownloader/HDoujinDownloader#427]
lately the downloads from niyaniya.moe are failing in 90% of cases

I've attached sample logs for a failing cases:
[1732017137-debug.log](https://github.com/user-attachments/files/17814779/1732017137-debug.log)
[1732017260-niyaniya.moe.log](https://github.com/user-attachments/files/17814780/1732017260-niyaniya.moe.log)

seems to be related to javascript execution as per the niyaniya.moe.log
```html
 <body>
    <div id="root">
      <div>
        <p>Loading...</p>
        <p>Please make sure to use the latest modern browsers to access this site.</p>
        <noscript>SchaleNetwork requires JavaScript to function.</noscript>
      </div>
    </div>
  </body>
```

\+ this in debug log
```
12:54:20 http        [x] Received 404 error from https://api.niyaniya.moe/books/detail/24178/f7d141ba9c69
```

any way to fix/avoid that?

Thanks in advance :)

**Comment by HDoujinDownloader** [comment]
@namekman was right, the API endpoint changed. Thanks for that!

I just uploaded a fix, so it should be resolved now. 👍

**Comment by Baine** [comment]
just tried, and working again. tysm!

> Thank you for the detailed report, by the way!

happy that you see it as such :) was primarily making sure that it's not caused by something on my end, and sharing the findings can't hurt in order to resolve the issue at hand.
keep it up 👍
