### ISSUE TITLE
Unable to Download from from Asurascans

### ISSUE THREAD

**Issue by ahmadi3d** [HDoujinDownloader/HDoujinDownloader#428]
From a couple of days ago you can't download from Asurascans, the domain has not changed, it seems to be a fetch chapter issue ? 
https://asuracomic.net/series/return-of-the-mount-hua-sect-fdaf4cf0

**Comment by HDoujinDownloader** [comment]
I just uploaded a fix (988565b), so it should be good now! Let me know if you continue to have problems with it.

**Comment by ahmadi3d** [comment]
Thank you! The issue has been resolved its just that some new chapters are having some issues, only a single page from all the page of the chapter is begin captured.
Example:
https://asuracomic.net/series/swordmasters-youngest-son-06d1c859
Chapter 139
https://asuracomic.net/series/swordmasters-youngest-son-06d1c859/chapter/139
If you try to download it only a single page is downloaded.

Thanks agian!

**Comment by HDoujinDownloader** [comment]
This should be resolved now thanks to a fix from @mrstan3772 (#429)!
