### ISSUE TITLE
Fix Asurascans website

### ISSUE THREAD

**Issue by ahmadi3d** [HDoujinDownloader/HDoujinDownloader#433]
Hello,
[AsuraScans](https://asuracomic.net/) has updated their website. The first issue seems to be that fetching the chapters has stopped working. Additionally, they have implemented an early chapter subscription model, where new chapters are only accessible after a delay. I would appreciate it if you could fix this issue and ensure that early chapters are only captured if they are accessible.

Finally, it would be great if you could add an authentication feature to the AsuraScans module. This would allow users to log in to their accounts, access early chapters, and benefit from the higher quality images that come with their subscriptions.

Thank you!

**Comment by HDoujinDownloader** [comment]
It should now get the chapter list again, and skip over unreleased chapters.

I did add login support, but it depends on some stuff I'm adding in the next program update, so it won't be working just yet. In the meantime, you can still log in manually using the built-in web browser by going _**Tools > Web Browser**_.
