### ISSUE TITLE
[Lezhin US] can't download mature content 

### ISSUE THREAD

**Issue by BereBereBeer** [HDoujinDownloader/HDoujinDownloader#439]
I can't add new titles or see the chapter list for the mature series, but it works for the all-ages ones, I can download the purchased chapters too.

I'm so sorry this seems to be a monthly issue

**Comment by HDoujinDownloader** [comment]
No need to apologize, it's not your fault this website updates so frequently. You're not the first person to mention this, either!

When testing on my end, I'm able to add 18+ content to the download queue and successfully run the download. It would be very helpful if you could generate a log file for me.

Go to **_Tools > Enable diagnostics_**, and then attempt to add one of the affected URLs to the download queue. A folder named "log" will be created in the same directory as HDoujin Downloader. Send me the log files inside, and I'll see what I can figure out! (You can send them to the email address on the "About" tab of the program.)

**Comment by HDoujinDownloader** [comment]
Interesting, thank you for the update! I don't think you did anything wrong; someone else reached out to me about intermittent failures recently too. Hopefully everything stays working for now.

I'll close this issue, but let me know if it starts happening again!
