### ISSUE TITLE
Fix download for readcomiconline.li

### ISSUE THREAD

**Issue by Crome696** [HDoujinDownloader/HDoujinDownloader#44]
Version: Version 2021.11.15
Host: https://readcomiconline.li/

Description: Multiple Pages not working on download. It might be an Anti-Spam mechanism or something. So you cannot download chapters anymore.

Sample: https://readcomiconline.li/Comic/Locke-Key-2008

**Comment by HDoujinDownloader** [comment]
> It might be an Anti-Spam mechanism or something

I think you're right about that. I've known this site to occasionally start displaying a captcha before allowing you to read any chapters, which can be verified by trying to open any chapter in your browser. If a captcha appears, solve it, and then [copy your session cookie into HDoujin Downloader](https://doujindownloader.com/copy-cookies/).

If that doesn't fix it, I know that some users have found success in using a VPN to get around the issue.

I think it depends on how aggressively you're scraping chapters. If you mess with the settings under **_Tools > Preferences > Timing & delays_**, you can set up rate limiting such that this problem is less likely to occur.

**Comment by Crome696** [comment]
I have checked the Website through an ordinary browser (regulary using Firefox combined with a few plugins). It seems it shows a lot of advertisment where you have to wait and click close. My personal guess would be, that those make trouble.
I´ve checked the lua files in order if i could *hack* a workaround into it but hadn´t found a quick solution.

**Comment by HDoujinDownloader** [comment]
Am I correct in assuming that it's able to get the chapters list correctly, and just failing to download any images? When you right-click the item in the download queue and select "Choose Chapters", do the chapters appear as expected?

If it's seeing the chapters but failing to find the images, let's try this: Enable logging by going to **_Help > Enable Diagnostics_**, then get the URL of one of the **chapters** from your example comic (for example, the URL of the first chapter). Add it to the download queue, and then you should end up with a "log" folder with a file inside of it named something along the lines of "XXXXXXXXXX-readcomiconline.li.log". It will contain the HTML of the webpage. Send it to me, and I'll check it out.

**Comment by Crome696** [comment]
Here is the log file.

I´m able to see the chapters but when checking pages it failed.

[1637585785-readcomiconline.li.log](https://github.com/HDoujinDownloader/HDoujinDownloader/files/7581141/1637585785-readcomiconline.li.log)

Sadly this repo only contains the modules else i would had checked if i could debug it myself.

**Comment by HDoujinDownloader** [comment]
> Here is the log file.

Thanks a lot! The only thing is, I need it to be generated from of the **chapter** URLs. For example, the URL of the first issue listed. I apologize for the confusion here.

> Sadly this repo only contains the modules else i would had checked if i could debug it myself.

It's the modules that are important in this case. You can see the module for this site [here](https://github.com/HDoujinDownloader/HDoujinDownloader/blob/master/modules/lua/ReadComicOnline.lua). It's the `GetPages` function that's in charge of getting the page list, and inside of it you can see the regular expression that extracts the image URLs. If you want to mess with it, you can call `Log(whatever)` on pretty much any object to see its current state. In this case, `Log(dom)` will output the HTML of the page and perhaps shed some light on why the regular expression isn't matching anything.

**Comment by HDoujinDownloader** [comment]
This site now aggressively displays captchas (reCAPTCHA v2) every few chapters opened. 

My previous suggestion was to solve the captcha in your browser and copy the session cookie over to HDoujin Downloader, but this is ineffective now (the cookie doesn't work and the captcha is triggered so often that it's not even worth it).

**Comment by HDoujinDownloader** [comment]
Never mind, I fixed it (1b8a056).

If downloads start failing because of the captcha, follow the instructions in [this comment](https://github.com/HDoujinDownloader/HDoujinDownloader/issues/44#issuecomment-975431953) to get them working again. The cookie you want is `b_token`.
