### ISSUE TITLE
can't download from author page on hentai2read

### ISSUE THREAD

**Issue by nammerduong** [HDoujinDownloader/HDoujinDownloader#46]
For example if I put in "https://hentai2read.com/hentai-list/author/kisaragi-gunma/" into HDoujinDownloader I always get "Error (page collection error) under status. I'm quite sure I was able to download from the author page before. It used to download all the doujins from the author if I pasted in that link. I only get an error now. I'm not sure when the issue started, I only just recently found out.

**Comment by HDoujinDownloader** [comment]
You're remembering correctly; this used to work until the support module for this site was moved to a Lua script. I just restored the functionality with 8ff10bc2c3377ceca7825a4b63e0252b96456af2, so it should be good now. ❤️
