### ISSUE TITLE
Fix download for allporncomic.com

### ISSUE THREAD

**Issue by asaiyink** [HDoujinDownloader/HDoujinDownloader#47]
This website was listed as being supported in the change logs, however it does not work. The link grabbing works as expected but the download does not work and just lists as completed with nothing downloaded.

**Comment by HDoujinDownloader** [comment]
This site seems to be working from my end with the latest release (v2021.12.13.1). 

It uses Cloudflare's anti-bot services, so you'll need to make sure you're using the [FlareSolverr plugin](https://github.com/HDoujinDownloader/HDoujinDownloader/wiki/FlareSolverr-IUAM-Challenge-Solver). I've removed the recommendation to use v1.2.9 and now recommend using the latest version (v2.1.0).

If you still have trouble after that, let me know and we can figure it out from there.

**Comment by asaiyink** [comment]
Yeah its still not working. I've installed it as per the instructions but it still marks instantly as completed with nothing done. Let me know what info you need from me to continue trouble shooting

**Comment by HDoujinDownloader** [comment]
The following log was sent to me in response to this issue:

```
16:33:59 http        [x] Exception was thrown when accessing https://allporncomic.com/porncomic/motherhood-a-tale-of-love-amarsroshtaa/: System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond xxx.xxx.xxx.xx:443 ( I redacted this )
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
```

**Comment by asaiyink** [comment]
So what should I do?

**Comment by HDoujinDownloader** [comment]
Glad to hear it.

I had reports from a few other users for different sites that would result in the same error message, but it eventually went away on its own (apparently). It's very strange, but I guess I'm glad it's resolved for now.
