### ISSUE TITLE
Fix download for manga18fx.com

### ISSUE THREAD

**Issue by Twilight666** [HDoujinDownloader/HDoujinDownloader#51]
Since a few hours ago manga18fx isn't working.
A couple of times it recognised the url to add the chapter but failed to start downloading (it wrote collection error, but I have since rebooted it and lost the log)
but now it keeps failing.
I checked the logs and get this:

> 11:39:38 queue       [!] Skipped https://manga18fx.com/manga/ones-in-laws-virgins/chapter-86 (Invalid response or missing/outdated module)

It happens with whaterver url I try

**Comment by Twilight666** [comment]
I don't know what happened or when, but it looks like it's working again
I had HDoujin open with the monitor clipboard option active and I saw a storyhad been added successfully
I tried to download it and it worked
It looks like it works properly now

**Comment by HDoujinDownloader** [comment]
Glad to hear it! :heart:
