### ISSUE TITLE
Fix download for hitomi.la

### ISSUE THREAD

**Issue by RA5Dgz2L46** [HDoujinDownloader/HDoujinDownloader#55]
I keep getting Error (Page Collection Error) when downloading from hitomi.la

**Comment by HDoujinDownloader** [comment]
Downloads from hitomi.la should be working the latest release. Make sure you're updated to version 2022.1.3.0 and that your modules are up to date. They should be updated automatically every time you restart the program, but you can sync manually by going to **_Tools > Module Browser > Options_** and clicking the "Sync Now" button.

If that doesn't work, open the log by going to **_Tools > Log Viewer_**, attempt to start a download, and then send me the resulting log content.

**Comment by RA5Dgz2L46** [comment]
I had the latest version. Tried "Sync Now" and restarted downloads. It works now. Thanks.
