### ISSUE TITLE
Fix download for mangahosted.com

### ISSUE THREAD

**Issue by Fotguedes** [HDoujinDownloader/HDoujinDownloader#57]
It seems that they updated their site and even with website module I can't manage it to work.
Searching through Github commits and issues it appears that the site used to be

br.mangahost.com

And now it's

https://mangahosted.com/

If I try to access the first URL it already redirect to the second one

**Comment by HDoujinDownloader** [comment]
Thanks for letting me know! I've uploaded a fix (d606c95), and the site should now be working the next time you restart the program.
