### ISSUE TITLE
Add support for neoxscans.net

### ISSUE THREAD

**Issue by Fotguedes** [HDoujinDownloader/HDoujinDownloader#58]
Could you please add support for NeoxScans
https://neoxscans.net/

I already used it with Madara in other app, but I would love to use it in HDoujin

Tks in advance!

**Comment by HDoujinDownloader** [comment]
Support has now been added with ca2b775!

This site uses Cloudflare's anti-bot features, so make sure you're using the [FlareSolverr plugin](https://github.com/HDoujinDownloader/HDoujinDownloader/wiki/FlareSolverr-IUAM-Challenge-Solver).
