### ISSUE TITLE
autor/circle and other tags don't work on hitomi.la

### ISSUE THREAD

**Issue by yami-no-tusbas** [HDoujinDownloader/HDoujinDownloader#63]
Add any doujin, circle will be unknown, artist too, edit manga information show tags are fine, but Author/Circle, Artist & Description are empty.

Tested in Version 2022.1.3

**Comment by HDoujinDownloader** [comment]
I just uploaded a fix! Restart HDoujin Downloader and give it another shot, and the metadata should appear normally again.

If you find anything it's not working for, send me an example gallery and I'll check it out.
