### ISSUE TITLE
Fix download for toptoonplus.com

### ISSUE THREAD

**Issue by HDoujinDownloader** [HDoujinDownloader/HDoujinDownloader#65]
Automated login for toptoonplus.com is no longer functional because of reCAPTCHA v3.

**Comment by HDoujinDownloader** [comment]
Downloads from TopToonPlus recently stopped working. The API endpoint used to get the image list (`/check/isUsableEpisode`) no longer returns the image list. 

The new endpoint is `/api/v1/page/viewer`, which requires both a `viewerToken` parameter and `token` header in order to access. Both tokens have unique values.

**Comment by red111** [comment]
is there any fix to this problem soon?

**Comment by HDoujinDownloader** [comment]
This has now been fixed with commit b2fbb84ccb233ad9c76c7d73d14be75a29daa5de.

Automated log-in still isn't working due to reCAPTCHA and probably won't be implemented, but you can log in manually by following the instructions [here](https://github.com/HDoujinDownloader/HDoujinDownloader/wiki/Downloading-from-Toptoon-Plus).

**Comment by red111** [comment]
I followed the instructions and after I copied the token value and put it in Site Preferences ,HDoujin stopped downloading from toptoonplus as when I copy the chapter link it doesn't appear in the downloading list.

**Comment by HDoujinDownloader** [comment]
So it stopped working entirely after copying your token value into HDoujin Downloader, even for episodes you can access without an account?

My best guess would be that it wasn't copied exactly, and the API requests are returning an error because of it. You can check what's happening by going to **_Tools > Log Viewer_** and attempting to download. Errors will appear in red. If you want, you can copy the contents of the log here and I'll check it out.

For the record, the token value should look something like this (with no whitespace): `e48adb85-d6c5-465e-ba55-7f16b785fc63`

**Comment by red111** [comment]
Thank you very much ,It worked.
