### ISSUE TITLE
Executable getting detected as Win32/Detplock

### ISSUE THREAD

**Issue by namekman** [HDoujinDownloader/HDoujinDownloader#66]
HDoujinDownloader executable is getting recognised by Windows Security as Win32/Detplock on Windows 10.
![2022-02-08](https://user-images.githubusercontent.com/51320875/152896814-dd9d81dc-ffb2-4bb0-8bc6-6c2b1c6316f7.png)

**Comment by HDoujinDownloader** [comment]
Thanks for the heads-up. I just submitted a false-positive report, so hopefully this is resolved soon.

**Comment by HDoujinDownloader** [comment]
All right, I got the following response:

>We cannot reproduce any detection on the file. If the detection is still observed, follow the steps below to capture support log files from the system reporting detection.
>
>From an elevated command prompt, change to directory "%programfiles%\windows defender" and execute mpcmdrun.exe with option GetFiles:
cd "%programfiles%\windows defender"
mpcmdrun.exe -GetFiles
>
>All created log files will be compressed into MPSupportFiles.cab. Please send us the detected file and MPSupportFiles.cab using https://aka.ms/wdsi. We will continue the investigation once we receive the support log files.

Is this from Windows Defender? It looks to me like it's complaining about `HDoujin Downloader.exe` specifically, which is what I sent in the submission. Maybe try updating Windows Defender's definitions and seeing if it's still flagged. If it is, let me know.

**Comment by namekman** [comment]
It seems to work again with yesterday's definitions, thanks!
