### ISSUE TITLE
Add support for bilibilicomics.com

### ISSUE THREAD

**Issue by alen098** [HDoujinDownloader/HDoujinDownloader#68]
Add support for the site [BILIBILI COMICS](https://www.bilibilicomics.com).

- Also a menu to choose quality of the image to download from [BILIBILI COMICS](https://www.bilibilicomics.com), i.e; RAW, HD AND SD.

**Comment by HDoujinDownloader** [comment]
Login support should be implemented as noted in #85.

**Comment by HDoujinDownloader** [comment]
Support for BILIBILI COMICS has been added with commit 8c73797cacedd9587ff1cfacb1b2282779bb9680. While there's no automated login support right now, you can log in by copying your authorization token as described [here](https://github.com/HDoujinDownloader/HDoujinDownloader/wiki/Getting-Bearer-Token-From-Web-Browser).

See #85 for progress updates on adding login support for this site.
