### ISSUE TITLE
PAY TO DOWNLOAD?

### ISSUE THREAD

**Issue by masterofobzene** [HDoujinDownloader/HDoujinDownloader#69]
what? I'm using the "free version" with 25 download per day?

FUCK OFF.

**Comment by HDoujinDownloader** [comment]
:disappointed: 

I hear you. I don't want to have to monetize it, but keeping this thing working eats up the majority of my time. It's a one-time payment that gets you a lifetime of my continued work, and I've been maintaining this thing for almost 8 years now. This is the furthest thing from profitable, I assure you.

If the cost is an issue for you, you're welcome to HMU over email and we can figure something out.

By the way, the modules are openly available: https://github.com/HDoujinDownloader/HDoujinDownloader/tree/master/modules/lua
You're welcome to implement your own client if you want to.
