### ISSUE TITLE
Add support for h5.mangatoon.mobi

### ISSUE THREAD

**Issue by muser0** [HDoujinDownloader/HDoujinDownloader#71]
Add support for the site [Mangatoon](https://h5.mangatoon.mobi).

Example Manhua - [Swallow An Immortal World](https://h5.mangatoon.mobi/contents/detail/858141).

It is an alterative website of Mangatoon.mobi

**Comment by HDoujinDownloader** [comment]
Support for this site has now been added, so it should be working the next time you restart HDoujin Downloader. 💪

I didn't add any login support, so let me know if that's something you need.
