### ISSUE TITLE
Mangadex issue - completed/ongoing status

### ISSUE THREAD

**Issue by MelanieTanaka** [HDoujinDownloader/HDoujinDownloader#76]
Hello,

There seems to be an issue with mangadex and the "status" used for bookmarks.
Doujindownloader seems to use the "publication status" to determine this on mangadex, however mangadex is referring to the real world status and not the scanlation status.

Example this manga: https://mangadex.org/title/513ed884-79e3-44bf-ae0b-0c494fb897b2

The publication status is marked as completed, but the scans are not completed. The problem I am having is these get marked as completed in my bookmarks and I have to manually force them to check for new chapters. This also prevents me for confidently clearing out "completed" bookmarks because I know a not insignificant portion of them probably are still ongoing in terms of scanlation/chapter releases.

Some data that can maybe be used to help with this is mangadex tends to provide the "final chapter" info as well, for the above link it gives us:

` Final Chapter
Volume 16 , Chapter 159 `

Maybe if that info does not match the latest chapter you can set it to "ongoing" instead of "completed"?

There is also the "END" icon visible on the final chapter of manga who are actually completed for example on this manga: https://mangadex.org/title/7d32ba73-def9-4ef5-a062-00de9f5dec7d/franken-fran

I've set them manually to "ongoing" for now on titles I care a lot about but I have about 4000 bookmarks split on 2 instances of the app and I estimate half or more are on mangadex so it's become a bit of a nightmare :)

**Comment by HDoujinDownloader** [comment]
Thanks a lot for the details!

If you manually update to the [latest pre-release](https://github.com/HDoujinDownloader/HDoujinDownloader/releases/tag/2022.3.10.0-rc.3), I've got this implemented now. You'll find a new setting under **_Tools > Site Preferences > MangaDex_** called "Prefer scanlation status over publishing status". Check that off, and it should do what you want.

Let me know if you encounter any problems!

**Comment by HDoujinDownloader** [comment]
Thanks for the examples! You were right about the cause-- I had it only checking the most recently-uploaded chapter (also `lastVolume` is `null` for manga, which I didn't realize yesterday).

I just uploaded another fix!

> Also one weird bug with configuring the new option checkbox for "Prefer scanlation status over publishing status"
If you go into the mangadex site settings, check the box and close out it does not save the config.

I'm not sure about this, though. I wasn't able to reproduce the problem on either Windows 8.1 or Windows 10. May I ask what operating system you're using?

**Comment by MelanieTanaka** [comment]
I'm on server 2019. It's very odd since it happened on the first time setting up but I can't replicate it anymore. Once the setting actually saved it works 100% normal. I have a second instance (second VM, 2019) running the exact same setup for my other half of bookmarks so when this one is completed maybe will see if it happens again.
Guess if it's a real bug will see reports of it in the future, for now can say it's the IT Ghost.


For the status fix will do some test this weekend and update here how it goes. Have thousand of bookmarks so if something exist that can break it I'll probably run into it :P

Thanks a lot for adding this!

**Comment by HDoujinDownloader** [comment]
Spooky. 😱 I'll consider contacting a software exorcist. 

Anyway, no problem!
