### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Natoram** [HDoujinDownloader/HDoujinDownloader#83]
Please add toptoonplus and toptoon.com

**Comment by HDoujinDownloader** [comment]
Both sites should be working now with 9034cadab6228d475e290c78ec6bb4e256f407a7 and b2fbb84ccb233ad9c76c7d73d14be75a29daa5de.

While there is no automated login support for Toptoon Plus right now (#65), you can log in manually by following the instructions [here](https://github.com/HDoujinDownloader/HDoujinDownloader/wiki/Downloading-from-Toptoon-Plus).

I haven't added login support for Toptoon yet, but I've created a new issue to track progress on that feature (#86).
