### ISSUE TITLE
Add login support for bilibilicomics.com

### ISSUE THREAD

**Issue by ghost** [HDoujinDownloader/HDoujinDownloader#85]
- [Bilibili comics](https://www.bilibilicomics.com/) put up a paywall for comics. After paying coins or waiting for certain time the episodes will unlock. I tried to download the unlocked episodes with hakuneko and the downloaded folder shows only the first two images.
- Many comics on this site are inaccessible without an account.
- Add login support for [bilibili comics](https://www.bilibilicomics.com/).
- A continuation of #68.

**Comment by alen098** [comment]
A continuation of #68.

**Comment by HDoujinDownloader** [comment]
Thanks for the clarification. 😉 I'll reference this issue in the other one and close this one for now.

**Comment by HDoujinDownloader** [comment]
Support for BILIBILI COMICS has been added with commit 8c73797cacedd9587ff1cfacb1b2282779bb9680 (#68). While there's no automated login support right now, you can log in by copying your authorization token as described [here](https://github.com/HDoujinDownloader/HDoujinDownloader/wiki/Getting-Bearer-Token-From-Web-Browser).

That said, it seems feasible to automate the login process. The flow looks like this:

1. A request to `/twirp/global.v1.Comic/GetPasswordPk` returns a public key used to encrypt the user's password.
2. A request with the encrypted password is sent to `/twirp/global.v1.User/Login`, which returns a JSON object with an `access_token` property. This property is sent with future API requests in the `authorization` header to authenticate the user.

**Comment by alen098** [comment]
Automated login process will be much appreciated. Looking forward to it.

**Comment by HDoujinDownloader** [comment]
Closing this issue since Bilibili Comics no longer exists, but see #342.
