### ISSUE TITLE
Add support for h5.mangatoon.mobi

### ISSUE THREAD

**Issue by deanwinch1** [HDoujinDownloader/HDoujinDownloader#91]
- Site: https://h5.mangatoon.mobi/
- Manga List: https://h5.mangatoon.mobi/
- Manga example: https://h5.mangatoon.mobi/contents/detail/5
- Chapter online viewer example: https://h5.mangatoon.mobi/cartoons/watch/5/108302

Languages
- English

- It is an alternative domain of [Manga Toon](https://mangatoon.mobi/).

**Comment by HDoujinDownloader** [comment]
Duplicate of #71.
