### ISSUE TITLE
Add support for webnovel.com

### ISSUE THREAD

**Issue by deanwinch1** [HDoujinDownloader/HDoujinDownloader#93]
Add support for [webnovel](https://webnovel.com).

Also add login support for [webnovel](https://webnovel.com), some of the content requires an account.

**Comment by HDoujinDownloader** [comment]
For my own reference, this site does indeed have manga in addition to web novels. For example: https://www.webnovel.com/comic/tales-of-demons-and-gods_14622895506049901

**Comment by HDoujinDownloader** [comment]
Support for the site has now been added, but I need more time to get the login working (#95).
