### ISSUE TITLE
Taking my commit

### ISSUE THREAD

**Issue by WhoAreYouPeople** [HDoujinDownloader/HDoujinDownloader#99]
https://github.com/WhoAreYouPeople/FMD2/commit/7f93c209a7809f9ccfb70a4707f33ee3f2e6d975

https://github.com/HDoujinDownloader/HDoujinDownloader/commit/92734afe628bb70678eb1f6810ba0db98258f677

Looks like you took my fix, and then didn't credit me.

**Comment by HDoujinDownloader** [comment]
What part are you claiming was taken, the change from `data-src` to `data-lazy-src`? The image URL was moved to a different attribute, what do you expect?

Nothing was copied here.

**Comment by WhoAreYouPeople** [comment]
My issue is not with the fix, my issue is that the problem had been going on for weeks. And then the three days after I fixed it for FMD2, you applied the same fix.

**Comment by HDoujinDownloader** [comment]
I don't know how the issue was occurring for. I just fix 'em when someone tells me they're broken.

Once again, nothing was copied here.
